// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AccountLockdownInitParameters struct {

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	DeactivateUser *bool `json:"deactivateUser,omitempty" tf:"deactivate_user,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	DeleteSessions *bool `json:"deleteSessions,omitempty" tf:"delete_sessions,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	RevokeTokens *bool `json:"revokeTokens,omitempty" tf:"revoke_tokens,omitempty"`

	// (String)
	SelfServiceCompletionFlow *string `json:"selfServiceCompletionFlow,omitempty" tf:"self_service_completion_flow,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	SetUnusablePassword *bool `json:"setUnusablePassword,omitempty" tf:"set_unusable_password,omitempty"`
}

type AccountLockdownObservation struct {

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	DeactivateUser *bool `json:"deactivateUser,omitempty" tf:"deactivate_user,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	DeleteSessions *bool `json:"deleteSessions,omitempty" tf:"delete_sessions,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	RevokeTokens *bool `json:"revokeTokens,omitempty" tf:"revoke_tokens,omitempty"`

	// (String)
	SelfServiceCompletionFlow *string `json:"selfServiceCompletionFlow,omitempty" tf:"self_service_completion_flow,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	SetUnusablePassword *bool `json:"setUnusablePassword,omitempty" tf:"set_unusable_password,omitempty"`
}

type AccountLockdownParameters struct {

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	DeactivateUser *bool `json:"deactivateUser,omitempty" tf:"deactivate_user,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	DeleteSessions *bool `json:"deleteSessions,omitempty" tf:"delete_sessions,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	RevokeTokens *bool `json:"revokeTokens,omitempty" tf:"revoke_tokens,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	SelfServiceCompletionFlow *string `json:"selfServiceCompletionFlow,omitempty" tf:"self_service_completion_flow,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	SetUnusablePassword *bool `json:"setUnusablePassword,omitempty" tf:"set_unusable_password,omitempty"`
}

// AccountLockdownSpec defines the desired state of AccountLockdown
type AccountLockdownSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AccountLockdownParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccountLockdownInitParameters `json:"initProvider,omitempty"`
}

// AccountLockdownStatus defines the observed state of AccountLockdown.
type AccountLockdownStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AccountLockdownObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccountLockdown is the Schema for the AccountLockdowns API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,authentik}
type AccountLockdown struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   AccountLockdownSpec   `json:"spec"`
	Status AccountLockdownStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountLockdownList contains a list of AccountLockdowns
type AccountLockdownList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountLockdown `json:"items"`
}

// Repository type metadata.
var (
	AccountLockdown_Kind             = "AccountLockdown"
	AccountLockdown_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountLockdown_Kind}.String()
	AccountLockdown_KindAPIVersion   = AccountLockdown_Kind + "." + CRDGroupVersion.String()
	AccountLockdown_GroupVersionKind = CRDGroupVersion.WithKind(AccountLockdown_Kind)
)

func init() {
	SchemeBuilder.Register(&AccountLockdown{}, &AccountLockdownList{})
}
