//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Settings) DeepCopyInto(out *Settings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Settings.
func (in *Settings) DeepCopy() *Settings {
	if in == nil {
		return nil
	}
	out := new(Settings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Settings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsInitParameters) DeepCopyInto(out *SettingsInitParameters) {
	*out = *in
	if in.Avatars != nil {
		in, out := &in.Avatars, &out.Avatars
		*out = new(string)
		**out = **in
	}
	if in.DefaultTokenDuration != nil {
		in, out := &in.DefaultTokenDuration, &out.DefaultTokenDuration
		*out = new(string)
		**out = **in
	}
	if in.DefaultTokenLength != nil {
		in, out := &in.DefaultTokenLength, &out.DefaultTokenLength
		*out = new(float64)
		**out = **in
	}
	if in.DefaultUserChangeEmail != nil {
		in, out := &in.DefaultUserChangeEmail, &out.DefaultUserChangeEmail
		*out = new(bool)
		**out = **in
	}
	if in.DefaultUserChangeName != nil {
		in, out := &in.DefaultUserChangeName, &out.DefaultUserChangeName
		*out = new(bool)
		**out = **in
	}
	if in.DefaultUserChangeUsername != nil {
		in, out := &in.DefaultUserChangeUsername, &out.DefaultUserChangeUsername
		*out = new(bool)
		**out = **in
	}
	if in.EventRetention != nil {
		in, out := &in.EventRetention, &out.EventRetention
		*out = new(string)
		**out = **in
	}
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = new(string)
		**out = **in
	}
	if in.FooterLinks != nil {
		in, out := &in.FooterLinks, &out.FooterLinks
		*out = make([]map[string]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]*string, len(*in))
				for key, val := range *in {
					var outVal *string
					if val == nil {
						(*out)[key] = nil
					} else {
						inVal := (*in)[key]
						in, out := &inVal, &outVal
						*out = new(string)
						**out = **in
					}
					(*out)[key] = outVal
				}
			}
		}
	}
	if in.GdprCompliance != nil {
		in, out := &in.GdprCompliance, &out.GdprCompliance
		*out = new(bool)
		**out = **in
	}
	if in.Impersonation != nil {
		in, out := &in.Impersonation, &out.Impersonation
		*out = new(bool)
		**out = **in
	}
	if in.PaginationDefaultPageSize != nil {
		in, out := &in.PaginationDefaultPageSize, &out.PaginationDefaultPageSize
		*out = new(float64)
		**out = **in
	}
	if in.PaginationMaxPageSize != nil {
		in, out := &in.PaginationMaxPageSize, &out.PaginationMaxPageSize
		*out = new(float64)
		**out = **in
	}
	if in.ReputationLowerLimit != nil {
		in, out := &in.ReputationLowerLimit, &out.ReputationLowerLimit
		*out = new(float64)
		**out = **in
	}
	if in.ReputationUpperLimit != nil {
		in, out := &in.ReputationUpperLimit, &out.ReputationUpperLimit
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsInitParameters.
func (in *SettingsInitParameters) DeepCopy() *SettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsList) DeepCopyInto(out *SettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Settings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsList.
func (in *SettingsList) DeepCopy() *SettingsList {
	if in == nil {
		return nil
	}
	out := new(SettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsObservation) DeepCopyInto(out *SettingsObservation) {
	*out = *in
	if in.Avatars != nil {
		in, out := &in.Avatars, &out.Avatars
		*out = new(string)
		**out = **in
	}
	if in.DefaultTokenDuration != nil {
		in, out := &in.DefaultTokenDuration, &out.DefaultTokenDuration
		*out = new(string)
		**out = **in
	}
	if in.DefaultTokenLength != nil {
		in, out := &in.DefaultTokenLength, &out.DefaultTokenLength
		*out = new(float64)
		**out = **in
	}
	if in.DefaultUserChangeEmail != nil {
		in, out := &in.DefaultUserChangeEmail, &out.DefaultUserChangeEmail
		*out = new(bool)
		**out = **in
	}
	if in.DefaultUserChangeName != nil {
		in, out := &in.DefaultUserChangeName, &out.DefaultUserChangeName
		*out = new(bool)
		**out = **in
	}
	if in.DefaultUserChangeUsername != nil {
		in, out := &in.DefaultUserChangeUsername, &out.DefaultUserChangeUsername
		*out = new(bool)
		**out = **in
	}
	if in.EventRetention != nil {
		in, out := &in.EventRetention, &out.EventRetention
		*out = new(string)
		**out = **in
	}
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = new(string)
		**out = **in
	}
	if in.FooterLinks != nil {
		in, out := &in.FooterLinks, &out.FooterLinks
		*out = make([]map[string]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]*string, len(*in))
				for key, val := range *in {
					var outVal *string
					if val == nil {
						(*out)[key] = nil
					} else {
						inVal := (*in)[key]
						in, out := &inVal, &outVal
						*out = new(string)
						**out = **in
					}
					(*out)[key] = outVal
				}
			}
		}
	}
	if in.GdprCompliance != nil {
		in, out := &in.GdprCompliance, &out.GdprCompliance
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Impersonation != nil {
		in, out := &in.Impersonation, &out.Impersonation
		*out = new(bool)
		**out = **in
	}
	if in.PaginationDefaultPageSize != nil {
		in, out := &in.PaginationDefaultPageSize, &out.PaginationDefaultPageSize
		*out = new(float64)
		**out = **in
	}
	if in.PaginationMaxPageSize != nil {
		in, out := &in.PaginationMaxPageSize, &out.PaginationMaxPageSize
		*out = new(float64)
		**out = **in
	}
	if in.ReputationLowerLimit != nil {
		in, out := &in.ReputationLowerLimit, &out.ReputationLowerLimit
		*out = new(float64)
		**out = **in
	}
	if in.ReputationUpperLimit != nil {
		in, out := &in.ReputationUpperLimit, &out.ReputationUpperLimit
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsObservation.
func (in *SettingsObservation) DeepCopy() *SettingsObservation {
	if in == nil {
		return nil
	}
	out := new(SettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsParameters) DeepCopyInto(out *SettingsParameters) {
	*out = *in
	if in.Avatars != nil {
		in, out := &in.Avatars, &out.Avatars
		*out = new(string)
		**out = **in
	}
	if in.DefaultTokenDuration != nil {
		in, out := &in.DefaultTokenDuration, &out.DefaultTokenDuration
		*out = new(string)
		**out = **in
	}
	if in.DefaultTokenLength != nil {
		in, out := &in.DefaultTokenLength, &out.DefaultTokenLength
		*out = new(float64)
		**out = **in
	}
	if in.DefaultUserChangeEmail != nil {
		in, out := &in.DefaultUserChangeEmail, &out.DefaultUserChangeEmail
		*out = new(bool)
		**out = **in
	}
	if in.DefaultUserChangeName != nil {
		in, out := &in.DefaultUserChangeName, &out.DefaultUserChangeName
		*out = new(bool)
		**out = **in
	}
	if in.DefaultUserChangeUsername != nil {
		in, out := &in.DefaultUserChangeUsername, &out.DefaultUserChangeUsername
		*out = new(bool)
		**out = **in
	}
	if in.EventRetention != nil {
		in, out := &in.EventRetention, &out.EventRetention
		*out = new(string)
		**out = **in
	}
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = new(string)
		**out = **in
	}
	if in.FooterLinks != nil {
		in, out := &in.FooterLinks, &out.FooterLinks
		*out = make([]map[string]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]*string, len(*in))
				for key, val := range *in {
					var outVal *string
					if val == nil {
						(*out)[key] = nil
					} else {
						inVal := (*in)[key]
						in, out := &inVal, &outVal
						*out = new(string)
						**out = **in
					}
					(*out)[key] = outVal
				}
			}
		}
	}
	if in.GdprCompliance != nil {
		in, out := &in.GdprCompliance, &out.GdprCompliance
		*out = new(bool)
		**out = **in
	}
	if in.Impersonation != nil {
		in, out := &in.Impersonation, &out.Impersonation
		*out = new(bool)
		**out = **in
	}
	if in.PaginationDefaultPageSize != nil {
		in, out := &in.PaginationDefaultPageSize, &out.PaginationDefaultPageSize
		*out = new(float64)
		**out = **in
	}
	if in.PaginationMaxPageSize != nil {
		in, out := &in.PaginationMaxPageSize, &out.PaginationMaxPageSize
		*out = new(float64)
		**out = **in
	}
	if in.ReputationLowerLimit != nil {
		in, out := &in.ReputationLowerLimit, &out.ReputationLowerLimit
		*out = new(float64)
		**out = **in
	}
	if in.ReputationUpperLimit != nil {
		in, out := &in.ReputationUpperLimit, &out.ReputationUpperLimit
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsParameters.
func (in *SettingsParameters) DeepCopy() *SettingsParameters {
	if in == nil {
		return nil
	}
	out := new(SettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsSpec) DeepCopyInto(out *SettingsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsSpec.
func (in *SettingsSpec) DeepCopy() *SettingsSpec {
	if in == nil {
		return nil
	}
	out := new(SettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsStatus) DeepCopyInto(out *SettingsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsStatus.
func (in *SettingsStatus) DeepCopy() *SettingsStatus {
	if in == nil {
		return nil
	}
	out := new(SettingsStatus)
	in.DeepCopyInto(out)
	return out
}
