// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *GoogleWorkspace) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Ldap) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MicrosoftEntra) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Oauth2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Proxy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Rac) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Radius) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SAML) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Scim) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Ssf) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WsFederation) Hub() {}
