// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RacInitParameters struct {
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=0`.
	ConnectionExpiry *string `json:"connectionExpiry,omitempty" tf:"connection_expiry,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	Settings *string `json:"settings,omitempty" tf:"settings,omitempty"`
}

type RacObservation struct {
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=0`.
	ConnectionExpiry *string `json:"connectionExpiry,omitempty" tf:"connection_expiry,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	Settings *string `json:"settings,omitempty" tf:"settings,omitempty"`
}

type RacParameters struct {

	// +kubebuilder:validation:Optional
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	// +kubebuilder:validation:Optional
	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=0`.
	// +kubebuilder:validation:Optional
	ConnectionExpiry *string `json:"connectionExpiry,omitempty" tf:"connection_expiry,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	// +kubebuilder:validation:Optional
	Settings *string `json:"settings,omitempty" tf:"settings,omitempty"`
}

// RacSpec defines the desired state of Rac
type RacSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RacParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RacInitParameters `json:"initProvider,omitempty"`
}

// RacStatus defines the observed state of Rac.
type RacStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RacObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Rac is the Schema for the Racs API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,authentik}
type Rac struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authorizationFlow) || (has(self.initProvider) && has(self.initProvider.authorizationFlow))",message="spec.forProvider.authorizationFlow is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RacSpec   `json:"spec"`
	Status RacStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RacList contains a list of Racs
type RacList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Rac `json:"items"`
}

// Repository type metadata.
var (
	Rac_Kind             = "Rac"
	Rac_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Rac_Kind}.String()
	Rac_KindAPIVersion   = Rac_Kind + "." + CRDGroupVersion.String()
	Rac_GroupVersionKind = CRDGroupVersion.WithKind(Rac_Kind)
)

func init() {
	SchemeBuilder.Register(&Rac{}, &RacList{})
}
