// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ScimInitParameters struct {

	// (String) Allowed values:
	// Allowed values:
	// - `token`
	// - `oauth`
	// Defaults to `token`.
	AuthMode *string `json:"authMode,omitempty" tf:"auth_mode,omitempty"`

	// (String) Slug of an OAuth source used for authentication
	// Slug of an OAuth source used for authentication
	AuthOauth *string `json:"authOauth,omitempty" tf:"auth_oauth,omitempty"`

	// (String) JSON format expected. Use jsonencode() to pass objects. Defaults to {}.
	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	AuthOauthParams *string `json:"authOauthParams,omitempty" tf:"auth_oauth_params,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `default`
	// - `aws`
	// - `slack`
	// - `sfdc`
	// - `webex`
	// - `vcenter`
	// Defaults to `default`.
	CompatibilityMode *string `json:"compatibilityMode,omitempty" tf:"compatibility_mode,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// (Boolean)
	ExcludeUsersServiceAccount *bool `json:"excludeUsersServiceAccount,omitempty" tf:"exclude_users_service_account,omitempty"`

	// (List of String)
	GroupFilters []*string `json:"groupFilters,omitempty" tf:"group_filters,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// (List of String)
	PropertyMappingsGroup []*string `json:"propertyMappingsGroup,omitempty" tf:"property_mappings_group,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to hours=1.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `hours=1`.
	ServiceProviderConfigCacheTimeout *string `json:"serviceProviderConfigCacheTimeout,omitempty" tf:"service_provider_config_cache_timeout,omitempty"`

	// (Number) Defaults to 100.
	// Defaults to `100`.
	SyncPageSize *float64 `json:"syncPageSize,omitempty" tf:"sync_page_size,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to minutes=30.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
	SyncPageTimeout *string `json:"syncPageTimeout,omitempty" tf:"sync_page_timeout,omitempty"`

	// (String, Sensitive)
	TokenSecretRef *v2.LocalSecretKeySelector `json:"tokenSecretRef,omitempty" tf:"-"`

	// (String)
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ScimObservation struct {

	// (String) Allowed values:
	// Allowed values:
	// - `token`
	// - `oauth`
	// Defaults to `token`.
	AuthMode *string `json:"authMode,omitempty" tf:"auth_mode,omitempty"`

	// (String) Slug of an OAuth source used for authentication
	// Slug of an OAuth source used for authentication
	AuthOauth *string `json:"authOauth,omitempty" tf:"auth_oauth,omitempty"`

	// (String) JSON format expected. Use jsonencode() to pass objects. Defaults to {}.
	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	AuthOauthParams *string `json:"authOauthParams,omitempty" tf:"auth_oauth_params,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `default`
	// - `aws`
	// - `slack`
	// - `sfdc`
	// - `webex`
	// - `vcenter`
	// Defaults to `default`.
	CompatibilityMode *string `json:"compatibilityMode,omitempty" tf:"compatibility_mode,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// (Boolean)
	ExcludeUsersServiceAccount *bool `json:"excludeUsersServiceAccount,omitempty" tf:"exclude_users_service_account,omitempty"`

	// (List of String)
	GroupFilters []*string `json:"groupFilters,omitempty" tf:"group_filters,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// (List of String)
	PropertyMappingsGroup []*string `json:"propertyMappingsGroup,omitempty" tf:"property_mappings_group,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to hours=1.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `hours=1`.
	ServiceProviderConfigCacheTimeout *string `json:"serviceProviderConfigCacheTimeout,omitempty" tf:"service_provider_config_cache_timeout,omitempty"`

	// (Number) Defaults to 100.
	// Defaults to `100`.
	SyncPageSize *float64 `json:"syncPageSize,omitempty" tf:"sync_page_size,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to minutes=30.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
	SyncPageTimeout *string `json:"syncPageTimeout,omitempty" tf:"sync_page_timeout,omitempty"`

	// (String)
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ScimParameters struct {

	// (String) Allowed values:
	// Allowed values:
	// - `token`
	// - `oauth`
	// Defaults to `token`.
	// +kubebuilder:validation:Optional
	AuthMode *string `json:"authMode,omitempty" tf:"auth_mode,omitempty"`

	// (String) Slug of an OAuth source used for authentication
	// Slug of an OAuth source used for authentication
	// +kubebuilder:validation:Optional
	AuthOauth *string `json:"authOauth,omitempty" tf:"auth_oauth,omitempty"`

	// (String) JSON format expected. Use jsonencode() to pass objects. Defaults to {}.
	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	// +kubebuilder:validation:Optional
	AuthOauthParams *string `json:"authOauthParams,omitempty" tf:"auth_oauth_params,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `default`
	// - `aws`
	// - `slack`
	// - `sfdc`
	// - `webex`
	// - `vcenter`
	// Defaults to `default`.
	// +kubebuilder:validation:Optional
	CompatibilityMode *string `json:"compatibilityMode,omitempty" tf:"compatibility_mode,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	ExcludeUsersServiceAccount *bool `json:"excludeUsersServiceAccount,omitempty" tf:"exclude_users_service_account,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	GroupFilters []*string `json:"groupFilters,omitempty" tf:"group_filters,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	PropertyMappingsGroup []*string `json:"propertyMappingsGroup,omitempty" tf:"property_mappings_group,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to hours=1.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `hours=1`.
	// +kubebuilder:validation:Optional
	ServiceProviderConfigCacheTimeout *string `json:"serviceProviderConfigCacheTimeout,omitempty" tf:"service_provider_config_cache_timeout,omitempty"`

	// (Number) Defaults to 100.
	// Defaults to `100`.
	// +kubebuilder:validation:Optional
	SyncPageSize *float64 `json:"syncPageSize,omitempty" tf:"sync_page_size,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to minutes=30.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
	// +kubebuilder:validation:Optional
	SyncPageTimeout *string `json:"syncPageTimeout,omitempty" tf:"sync_page_timeout,omitempty"`

	// (String, Sensitive)
	// +kubebuilder:validation:Optional
	TokenSecretRef *v2.LocalSecretKeySelector `json:"tokenSecretRef,omitempty" tf:"-"`

	// (String)
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// ScimSpec defines the desired state of Scim
type ScimSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ScimParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScimInitParameters `json:"initProvider,omitempty"`
}

// ScimStatus defines the observed state of Scim.
type ScimStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ScimObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Scim is the Schema for the Scims API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,authentik}
type Scim struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   ScimSpec   `json:"spec"`
	Status ScimStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScimList contains a list of Scims
type ScimList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Scim `json:"items"`
}

// Repository type metadata.
var (
	Scim_Kind             = "Scim"
	Scim_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Scim_Kind}.String()
	Scim_KindAPIVersion   = Scim_Kind + "." + CRDGroupVersion.String()
	Scim_GroupVersionKind = CRDGroupVersion.WithKind(Scim_Kind)
)

func init() {
	SchemeBuilder.Register(&Scim{}, &ScimList{})
}
