// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha1 "github.com/dhm116/provider-upjet-authentik/apis/cluster/provider/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Schedule.
func (mg *Schedule) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ModelID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ModelIDRef,
		Selector:     mg.Spec.ForProvider.ModelIDSelector,
		To: reference.To{
			List:    &v1alpha1.ScimList{},
			Managed: &v1alpha1.Scim{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ModelID")
	}
	mg.Spec.ForProvider.ModelID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ModelIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ModelID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ModelIDRef,
		Selector:     mg.Spec.InitProvider.ModelIDSelector,
		To: reference.To{
			List:    &v1alpha1.ScimList{},
			Managed: &v1alpha1.Scim{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ModelID")
	}
	mg.Spec.InitProvider.ModelID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ModelIDRef = rsp.ResolvedReference

	return nil
}
