apiVersion: property.authentik.goauthentik.io/v1alpha1
kind: MappingProviderSAML
metadata:
  annotations:
    meta.upbound.io/example-id: property/v1alpha1/mappingprovidersaml
  labels:
    testing.upbound.io/example-name: saml-aws-rolessessionname
  name: saml-aws-rolessessionname
spec:
  forProvider:
    expression: return user.email
    name: SAML AWS RoleSessionName
    samlName: https://aws.amazon.com/SAML/Attributes/RoleSessionName
