// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PlexInitParameters struct {

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	AllowFriends *bool `json:"allowFriends,omitempty" tf:"allow_friends,omitempty"`

	// (List of String)
	AllowedServers []*string `json:"allowedServers,omitempty" tf:"allowed_servers,omitempty"`

	// (String)
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	// (String)
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	EnrollmentFlow *string `json:"enrollmentFlow,omitempty" tf:"enrollment_flow,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `identifier`
	// - `name_link`
	// - `name_deny`
	// Defaults to `identifier`.
	GroupMatchingMode *string `json:"groupMatchingMode,omitempty" tf:"group_matching_mode,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Sensitive)
	PlexTokenSecretRef v2.SecretKeySelector `json:"plexTokenSecretRef" tf:"-"`

	// (String) Allowed values:
	// Allowed values:
	// - `all`
	// - `any`
	// Defaults to `any`.
	PolicyEngineMode *string `json:"policyEngineMode,omitempty" tf:"policy_engine_mode,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	Promoted *bool `json:"promoted,omitempty" tf:"promoted,omitempty"`

	// (String)
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// (String) Generated.
	// Generated.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `identifier`
	// - `email_link`
	// - `email_deny`
	// - `username_link`
	// - `username_deny`
	// Defaults to `identifier`.
	UserMatchingMode *string `json:"userMatchingMode,omitempty" tf:"user_matching_mode,omitempty"`

	// (String) Defaults to goauthentik.io/sources/%(slug)s.
	// Defaults to `goauthentik.io/sources/%(slug)s`.
	UserPathTemplate *string `json:"userPathTemplate,omitempty" tf:"user_path_template,omitempty"`
}

type PlexObservation struct {

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	AllowFriends *bool `json:"allowFriends,omitempty" tf:"allow_friends,omitempty"`

	// (List of String)
	AllowedServers []*string `json:"allowedServers,omitempty" tf:"allowed_servers,omitempty"`

	// (String)
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	// (String)
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	EnrollmentFlow *string `json:"enrollmentFlow,omitempty" tf:"enrollment_flow,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `identifier`
	// - `name_link`
	// - `name_deny`
	// Defaults to `identifier`.
	GroupMatchingMode *string `json:"groupMatchingMode,omitempty" tf:"group_matching_mode,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `all`
	// - `any`
	// Defaults to `any`.
	PolicyEngineMode *string `json:"policyEngineMode,omitempty" tf:"policy_engine_mode,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	Promoted *bool `json:"promoted,omitempty" tf:"promoted,omitempty"`

	// (String)
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// (String) Generated.
	// Generated.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `identifier`
	// - `email_link`
	// - `email_deny`
	// - `username_link`
	// - `username_deny`
	// Defaults to `identifier`.
	UserMatchingMode *string `json:"userMatchingMode,omitempty" tf:"user_matching_mode,omitempty"`

	// (String) Defaults to goauthentik.io/sources/%(slug)s.
	// Defaults to `goauthentik.io/sources/%(slug)s`.
	UserPathTemplate *string `json:"userPathTemplate,omitempty" tf:"user_path_template,omitempty"`
}

type PlexParameters struct {

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	AllowFriends *bool `json:"allowFriends,omitempty" tf:"allow_friends,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	AllowedServers []*string `json:"allowedServers,omitempty" tf:"allowed_servers,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	EnrollmentFlow *string `json:"enrollmentFlow,omitempty" tf:"enrollment_flow,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `identifier`
	// - `name_link`
	// - `name_deny`
	// Defaults to `identifier`.
	// +kubebuilder:validation:Optional
	GroupMatchingMode *string `json:"groupMatchingMode,omitempty" tf:"group_matching_mode,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Sensitive)
	// +kubebuilder:validation:Optional
	PlexTokenSecretRef v2.SecretKeySelector `json:"plexTokenSecretRef" tf:"-"`

	// (String) Allowed values:
	// Allowed values:
	// - `all`
	// - `any`
	// Defaults to `any`.
	// +kubebuilder:validation:Optional
	PolicyEngineMode *string `json:"policyEngineMode,omitempty" tf:"policy_engine_mode,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	Promoted *bool `json:"promoted,omitempty" tf:"promoted,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// (String) Generated.
	// Generated.
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `identifier`
	// - `email_link`
	// - `email_deny`
	// - `username_link`
	// - `username_deny`
	// Defaults to `identifier`.
	// +kubebuilder:validation:Optional
	UserMatchingMode *string `json:"userMatchingMode,omitempty" tf:"user_matching_mode,omitempty"`

	// (String) Defaults to goauthentik.io/sources/%(slug)s.
	// Defaults to `goauthentik.io/sources/%(slug)s`.
	// +kubebuilder:validation:Optional
	UserPathTemplate *string `json:"userPathTemplate,omitempty" tf:"user_path_template,omitempty"`
}

// PlexSpec defines the desired state of Plex
type PlexSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   PlexParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PlexInitParameters `json:"initProvider,omitempty"`
}

// PlexStatus defines the observed state of Plex.
type PlexStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PlexObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Plex is the Schema for the Plexs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type Plex struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientId) || (has(self.initProvider) && has(self.initProvider.clientId))",message="spec.forProvider.clientId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.plexTokenSecretRef)",message="spec.forProvider.plexTokenSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.slug) || (has(self.initProvider) && has(self.initProvider.slug))",message="spec.forProvider.slug is a required parameter"
	Spec   PlexSpec   `json:"spec"`
	Status PlexStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PlexList contains a list of Plexs
type PlexList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Plex `json:"items"`
}

// Repository type metadata.
var (
	Plex_Kind             = "Plex"
	Plex_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Plex_Kind}.String()
	Plex_KindAPIVersion   = Plex_Kind + "." + CRDGroupVersion.String()
	Plex_GroupVersionKind = CRDGroupVersion.WithKind(Plex_Kind)
)

func init() {
	SchemeBuilder.Register(&Plex{}, &PlexList{})
}
