// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type TelegramInitParameters struct {
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	BotToken *string `json:"botToken,omitempty" tf:"bot_token,omitempty"`

	BotUsername *string `json:"botUsername,omitempty" tf:"bot_username,omitempty"`

	// Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	EnrollmentFlow *string `json:"enrollmentFlow,omitempty" tf:"enrollment_flow,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Allowed values:
	// - `all`
	// - `any`
	// Defaults to `any`.
	PolicyEngineMode *string `json:"policyEngineMode,omitempty" tf:"policy_engine_mode,omitempty"`

	PreAuthenticationFlow *string `json:"preAuthenticationFlow,omitempty" tf:"pre_authentication_flow,omitempty"`

	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	PropertyMappingsGroup []*string `json:"propertyMappingsGroup,omitempty" tf:"property_mappings_group,omitempty"`

	// Defaults to `false`.
	RequestMessageAccess *bool `json:"requestMessageAccess,omitempty" tf:"request_message_access,omitempty"`

	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// Generated.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Allowed values:
	// - `identifier`
	// - `email_link`
	// - `email_deny`
	// - `username_link`
	// - `username_deny`
	// Defaults to `identifier`.
	UserMatchingMode *string `json:"userMatchingMode,omitempty" tf:"user_matching_mode,omitempty"`

	// Defaults to `goauthentik.io/sources/%(slug)s`.
	UserPathTemplate *string `json:"userPathTemplate,omitempty" tf:"user_path_template,omitempty"`
}

type TelegramObservation struct {
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	BotToken *string `json:"botToken,omitempty" tf:"bot_token,omitempty"`

	BotUsername *string `json:"botUsername,omitempty" tf:"bot_username,omitempty"`

	// Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	EnrollmentFlow *string `json:"enrollmentFlow,omitempty" tf:"enrollment_flow,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Allowed values:
	// - `all`
	// - `any`
	// Defaults to `any`.
	PolicyEngineMode *string `json:"policyEngineMode,omitempty" tf:"policy_engine_mode,omitempty"`

	PreAuthenticationFlow *string `json:"preAuthenticationFlow,omitempty" tf:"pre_authentication_flow,omitempty"`

	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	PropertyMappingsGroup []*string `json:"propertyMappingsGroup,omitempty" tf:"property_mappings_group,omitempty"`

	// Defaults to `false`.
	RequestMessageAccess *bool `json:"requestMessageAccess,omitempty" tf:"request_message_access,omitempty"`

	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// Generated.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Allowed values:
	// - `identifier`
	// - `email_link`
	// - `email_deny`
	// - `username_link`
	// - `username_deny`
	// Defaults to `identifier`.
	UserMatchingMode *string `json:"userMatchingMode,omitempty" tf:"user_matching_mode,omitempty"`

	// Defaults to `goauthentik.io/sources/%(slug)s`.
	UserPathTemplate *string `json:"userPathTemplate,omitempty" tf:"user_path_template,omitempty"`
}

type TelegramParameters struct {

	// +kubebuilder:validation:Optional
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	// +kubebuilder:validation:Optional
	BotToken *string `json:"botToken,omitempty" tf:"bot_token,omitempty"`

	// +kubebuilder:validation:Optional
	BotUsername *string `json:"botUsername,omitempty" tf:"bot_username,omitempty"`

	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	EnrollmentFlow *string `json:"enrollmentFlow,omitempty" tf:"enrollment_flow,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Allowed values:
	// - `all`
	// - `any`
	// Defaults to `any`.
	// +kubebuilder:validation:Optional
	PolicyEngineMode *string `json:"policyEngineMode,omitempty" tf:"policy_engine_mode,omitempty"`

	// +kubebuilder:validation:Optional
	PreAuthenticationFlow *string `json:"preAuthenticationFlow,omitempty" tf:"pre_authentication_flow,omitempty"`

	// +kubebuilder:validation:Optional
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// +kubebuilder:validation:Optional
	PropertyMappingsGroup []*string `json:"propertyMappingsGroup,omitempty" tf:"property_mappings_group,omitempty"`

	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	RequestMessageAccess *bool `json:"requestMessageAccess,omitempty" tf:"request_message_access,omitempty"`

	// +kubebuilder:validation:Optional
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`

	// Generated.
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Allowed values:
	// - `identifier`
	// - `email_link`
	// - `email_deny`
	// - `username_link`
	// - `username_deny`
	// Defaults to `identifier`.
	// +kubebuilder:validation:Optional
	UserMatchingMode *string `json:"userMatchingMode,omitempty" tf:"user_matching_mode,omitempty"`

	// Defaults to `goauthentik.io/sources/%(slug)s`.
	// +kubebuilder:validation:Optional
	UserPathTemplate *string `json:"userPathTemplate,omitempty" tf:"user_path_template,omitempty"`
}

// TelegramSpec defines the desired state of Telegram
type TelegramSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   TelegramParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TelegramInitParameters `json:"initProvider,omitempty"`
}

// TelegramStatus defines the observed state of Telegram.
type TelegramStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               TelegramObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Telegram is the Schema for the Telegrams API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type Telegram struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.botToken) || (has(self.initProvider) && has(self.initProvider.botToken))",message="spec.forProvider.botToken is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.botUsername) || (has(self.initProvider) && has(self.initProvider.botUsername))",message="spec.forProvider.botUsername is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.preAuthenticationFlow) || (has(self.initProvider) && has(self.initProvider.preAuthenticationFlow))",message="spec.forProvider.preAuthenticationFlow is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.slug) || (has(self.initProvider) && has(self.initProvider.slug))",message="spec.forProvider.slug is a required parameter"
	Spec   TelegramSpec   `json:"spec"`
	Status TelegramStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TelegramList contains a list of Telegrams
type TelegramList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Telegram `json:"items"`
}

// Repository type metadata.
var (
	Telegram_Kind             = "Telegram"
	Telegram_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Telegram_Kind}.String()
	Telegram_KindAPIVersion   = Telegram_Kind + "." + CRDGroupVersion.String()
	Telegram_GroupVersionKind = CRDGroupVersion.WithKind(Telegram_Kind)
)

func init() {
	SchemeBuilder.Register(&Telegram{}, &TelegramList{})
}
