// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha1 "github.com/dhm116/provider-authentik/apis/namespaced/certificate/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Docker.
func (mg *Docker) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.TLSAuthentication),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.TLSAuthenticationRef,
		Selector:     mg.Spec.ForProvider.TLSAuthenticationSelector,
		To: reference.To{
			List:    &v1alpha1.KeyPairList{},
			Managed: &v1alpha1.KeyPair{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.TLSAuthentication")
	}
	mg.Spec.ForProvider.TLSAuthentication = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.TLSAuthenticationRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.TLSVerification),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.TLSVerificationRef,
		Selector:     mg.Spec.ForProvider.TLSVerificationSelector,
		To: reference.To{
			List:    &v1alpha1.KeyPairList{},
			Managed: &v1alpha1.KeyPair{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.TLSVerification")
	}
	mg.Spec.ForProvider.TLSVerification = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.TLSVerificationRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.TLSAuthentication),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.TLSAuthenticationRef,
		Selector:     mg.Spec.InitProvider.TLSAuthenticationSelector,
		To: reference.To{
			List:    &v1alpha1.KeyPairList{},
			Managed: &v1alpha1.KeyPair{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.TLSAuthentication")
	}
	mg.Spec.InitProvider.TLSAuthentication = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.TLSAuthenticationRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.TLSVerification),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.TLSVerificationRef,
		Selector:     mg.Spec.InitProvider.TLSVerificationSelector,
		To: reference.To{
			List:    &v1alpha1.KeyPairList{},
			Managed: &v1alpha1.KeyPair{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.TLSVerification")
	}
	mg.Spec.InitProvider.TLSVerification = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.TLSVerificationRef = rsp.ResolvedReference

	return nil
}
