// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type MappingProviderMicrosoftEntraInitParameters struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MappingProviderMicrosoftEntraObservation struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MappingProviderMicrosoftEntraParameters struct {

	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// MappingProviderMicrosoftEntraSpec defines the desired state of MappingProviderMicrosoftEntra
type MappingProviderMicrosoftEntraSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MappingProviderMicrosoftEntraParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MappingProviderMicrosoftEntraInitParameters `json:"initProvider,omitempty"`
}

// MappingProviderMicrosoftEntraStatus defines the observed state of MappingProviderMicrosoftEntra.
type MappingProviderMicrosoftEntraStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               MappingProviderMicrosoftEntraObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MappingProviderMicrosoftEntra is the Schema for the MappingProviderMicrosoftEntras API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,authentik}
type MappingProviderMicrosoftEntra struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.expression) || (has(self.initProvider) && has(self.initProvider.expression))",message="spec.forProvider.expression is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   MappingProviderMicrosoftEntraSpec   `json:"spec"`
	Status MappingProviderMicrosoftEntraStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MappingProviderMicrosoftEntraList contains a list of MappingProviderMicrosoftEntras
type MappingProviderMicrosoftEntraList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MappingProviderMicrosoftEntra `json:"items"`
}

// Repository type metadata.
var (
	MappingProviderMicrosoftEntra_Kind             = "MappingProviderMicrosoftEntra"
	MappingProviderMicrosoftEntra_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MappingProviderMicrosoftEntra_Kind}.String()
	MappingProviderMicrosoftEntra_KindAPIVersion   = MappingProviderMicrosoftEntra_Kind + "." + CRDGroupVersion.String()
	MappingProviderMicrosoftEntra_GroupVersionKind = CRDGroupVersion.WithKind(MappingProviderMicrosoftEntra_Kind)
)

func init() {
	SchemeBuilder.Register(&MappingProviderMicrosoftEntra{}, &MappingProviderMicrosoftEntraList{})
}
