// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type MappingNotificationInitParameters struct {

	// (String)
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MappingNotificationObservation struct {

	// (String)
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MappingNotificationParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// MappingNotificationSpec defines the desired state of MappingNotification
type MappingNotificationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MappingNotificationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MappingNotificationInitParameters `json:"initProvider,omitempty"`
}

// MappingNotificationStatus defines the observed state of MappingNotification.
type MappingNotificationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               MappingNotificationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MappingNotification is the Schema for the MappingNotifications API. Manage Notification Property mappings
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,authentik}
type MappingNotification struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.expression) || (has(self.initProvider) && has(self.initProvider.expression))",message="spec.forProvider.expression is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   MappingNotificationSpec   `json:"spec"`
	Status MappingNotificationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MappingNotificationList contains a list of MappingNotifications
type MappingNotificationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MappingNotification `json:"items"`
}

// Repository type metadata.
var (
	MappingNotification_Kind             = "MappingNotification"
	MappingNotification_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MappingNotification_Kind}.String()
	MappingNotification_KindAPIVersion   = MappingNotification_Kind + "." + CRDGroupVersion.String()
	MappingNotification_GroupVersionKind = CRDGroupVersion.WithKind(MappingNotification_Kind)
)

func init() {
	SchemeBuilder.Register(&MappingNotification{}, &MappingNotificationList{})
}
