// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type MappingSourcePlexInitParameters struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MappingSourcePlexObservation struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MappingSourcePlexParameters struct {

	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// MappingSourcePlexSpec defines the desired state of MappingSourcePlex
type MappingSourcePlexSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MappingSourcePlexParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MappingSourcePlexInitParameters `json:"initProvider,omitempty"`
}

// MappingSourcePlexStatus defines the observed state of MappingSourcePlex.
type MappingSourcePlexStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               MappingSourcePlexObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MappingSourcePlex is the Schema for the MappingSourcePlexs API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,authentik}
type MappingSourcePlex struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.expression) || (has(self.initProvider) && has(self.initProvider.expression))",message="spec.forProvider.expression is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   MappingSourcePlexSpec   `json:"spec"`
	Status MappingSourcePlexStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MappingSourcePlexList contains a list of MappingSourcePlexs
type MappingSourcePlexList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MappingSourcePlex `json:"items"`
}

// Repository type metadata.
var (
	MappingSourcePlex_Kind             = "MappingSourcePlex"
	MappingSourcePlex_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MappingSourcePlex_Kind}.String()
	MappingSourcePlex_KindAPIVersion   = MappingSourcePlex_Kind + "." + CRDGroupVersion.String()
	MappingSourcePlex_GroupVersionKind = CRDGroupVersion.WithKind(MappingSourcePlex_Kind)
)

func init() {
	SchemeBuilder.Register(&MappingSourcePlex{}, &MappingSourcePlexList{})
}
