// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type BrandInitParameters struct {

	// (String) JSON format expected. Use jsonencode() to pass objects. Defaults to {}.
	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	Attributes *string `json:"attributes,omitempty" tf:"attributes,omitempty"`

	// (String)
	BrandingCustomCSS *string `json:"brandingCustomCss,omitempty" tf:"branding_custom_css,omitempty"`

	// (String) Defaults to /static/dist/assets/images/flow_background.jpg.
	// Defaults to `/static/dist/assets/images/flow_background.jpg`.
	BrandingDefaultFlowBackground *string `json:"brandingDefaultFlowBackground,omitempty" tf:"branding_default_flow_background,omitempty"`

	// (String)
	BrandingFavicon *string `json:"brandingFavicon,omitempty" tf:"branding_favicon,omitempty"`

	// (String)
	BrandingLogo *string `json:"brandingLogo,omitempty" tf:"branding_logo,omitempty"`

	// (String) Defaults to authentik.
	// Defaults to `authentik`.
	BrandingTitle *string `json:"brandingTitle,omitempty" tf:"branding_title,omitempty"`

	// (List of String)
	ClientCertificates []*string `json:"clientCertificates,omitempty" tf:"client_certificates,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	DefaultApplication *string `json:"defaultApplication,omitempty" tf:"default_application,omitempty"`

	// (String)
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String)
	FlowAuthentication *string `json:"flowAuthentication,omitempty" tf:"flow_authentication,omitempty"`

	// (String)
	FlowDeviceCode *string `json:"flowDeviceCode,omitempty" tf:"flow_device_code,omitempty"`

	// (String)
	FlowInvalidation *string `json:"flowInvalidation,omitempty" tf:"flow_invalidation,omitempty"`

	// (String)
	FlowLockdown *string `json:"flowLockdown,omitempty" tf:"flow_lockdown,omitempty"`

	// (String)
	FlowRecovery *string `json:"flowRecovery,omitempty" tf:"flow_recovery,omitempty"`

	// (String)
	FlowUnenrollment *string `json:"flowUnenrollment,omitempty" tf:"flow_unenrollment,omitempty"`

	// (String)
	FlowUserSettings *string `json:"flowUserSettings,omitempty" tf:"flow_user_settings,omitempty"`

	// (String)
	WebCertificate *string `json:"webCertificate,omitempty" tf:"web_certificate,omitempty"`
}

type BrandObservation struct {

	// (String) JSON format expected. Use jsonencode() to pass objects. Defaults to {}.
	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	Attributes *string `json:"attributes,omitempty" tf:"attributes,omitempty"`

	// (String)
	BrandingCustomCSS *string `json:"brandingCustomCss,omitempty" tf:"branding_custom_css,omitempty"`

	// (String) Defaults to /static/dist/assets/images/flow_background.jpg.
	// Defaults to `/static/dist/assets/images/flow_background.jpg`.
	BrandingDefaultFlowBackground *string `json:"brandingDefaultFlowBackground,omitempty" tf:"branding_default_flow_background,omitempty"`

	// (String)
	BrandingFavicon *string `json:"brandingFavicon,omitempty" tf:"branding_favicon,omitempty"`

	// (String)
	BrandingLogo *string `json:"brandingLogo,omitempty" tf:"branding_logo,omitempty"`

	// (String) Defaults to authentik.
	// Defaults to `authentik`.
	BrandingTitle *string `json:"brandingTitle,omitempty" tf:"branding_title,omitempty"`

	// (List of String)
	ClientCertificates []*string `json:"clientCertificates,omitempty" tf:"client_certificates,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	DefaultApplication *string `json:"defaultApplication,omitempty" tf:"default_application,omitempty"`

	// (String)
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String)
	FlowAuthentication *string `json:"flowAuthentication,omitempty" tf:"flow_authentication,omitempty"`

	// (String)
	FlowDeviceCode *string `json:"flowDeviceCode,omitempty" tf:"flow_device_code,omitempty"`

	// (String)
	FlowInvalidation *string `json:"flowInvalidation,omitempty" tf:"flow_invalidation,omitempty"`

	// (String)
	FlowLockdown *string `json:"flowLockdown,omitempty" tf:"flow_lockdown,omitempty"`

	// (String)
	FlowRecovery *string `json:"flowRecovery,omitempty" tf:"flow_recovery,omitempty"`

	// (String)
	FlowUnenrollment *string `json:"flowUnenrollment,omitempty" tf:"flow_unenrollment,omitempty"`

	// (String)
	FlowUserSettings *string `json:"flowUserSettings,omitempty" tf:"flow_user_settings,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	WebCertificate *string `json:"webCertificate,omitempty" tf:"web_certificate,omitempty"`
}

type BrandParameters struct {

	// (String) JSON format expected. Use jsonencode() to pass objects. Defaults to {}.
	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	// +kubebuilder:validation:Optional
	Attributes *string `json:"attributes,omitempty" tf:"attributes,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	BrandingCustomCSS *string `json:"brandingCustomCss,omitempty" tf:"branding_custom_css,omitempty"`

	// (String) Defaults to /static/dist/assets/images/flow_background.jpg.
	// Defaults to `/static/dist/assets/images/flow_background.jpg`.
	// +kubebuilder:validation:Optional
	BrandingDefaultFlowBackground *string `json:"brandingDefaultFlowBackground,omitempty" tf:"branding_default_flow_background,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	BrandingFavicon *string `json:"brandingFavicon,omitempty" tf:"branding_favicon,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	BrandingLogo *string `json:"brandingLogo,omitempty" tf:"branding_logo,omitempty"`

	// (String) Defaults to authentik.
	// Defaults to `authentik`.
	// +kubebuilder:validation:Optional
	BrandingTitle *string `json:"brandingTitle,omitempty" tf:"branding_title,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	ClientCertificates []*string `json:"clientCertificates,omitempty" tf:"client_certificates,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	DefaultApplication *string `json:"defaultApplication,omitempty" tf:"default_application,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	FlowAuthentication *string `json:"flowAuthentication,omitempty" tf:"flow_authentication,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	FlowDeviceCode *string `json:"flowDeviceCode,omitempty" tf:"flow_device_code,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	FlowInvalidation *string `json:"flowInvalidation,omitempty" tf:"flow_invalidation,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	FlowLockdown *string `json:"flowLockdown,omitempty" tf:"flow_lockdown,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	FlowRecovery *string `json:"flowRecovery,omitempty" tf:"flow_recovery,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	FlowUnenrollment *string `json:"flowUnenrollment,omitempty" tf:"flow_unenrollment,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	FlowUserSettings *string `json:"flowUserSettings,omitempty" tf:"flow_user_settings,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	WebCertificate *string `json:"webCertificate,omitempty" tf:"web_certificate,omitempty"`
}

// BrandSpec defines the desired state of Brand
type BrandSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BrandParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BrandInitParameters `json:"initProvider,omitempty"`
}

// BrandStatus defines the observed state of Brand.
type BrandStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               BrandObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Brand is the Schema for the Brands API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,authentik}
type Brand struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.domain) || (has(self.initProvider) && has(self.initProvider.domain))",message="spec.forProvider.domain is a required parameter"
	Spec   BrandSpec   `json:"spec"`
	Status BrandStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BrandList contains a list of Brands
type BrandList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Brand `json:"items"`
}

// Repository type metadata.
var (
	Brand_Kind             = "Brand"
	Brand_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Brand_Kind}.String()
	Brand_KindAPIVersion   = Brand_Kind + "." + CRDGroupVersion.String()
	Brand_GroupVersionKind = CRDGroupVersion.WithKind(Brand_Kind)
)

func init() {
	SchemeBuilder.Register(&Brand{}, &BrandList{})
}
