// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"

	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha11 "github.com/dhm116/provider-upjet-authentik/apis/namespaced/authentik/v1alpha1"
	v1alpha1 "github.com/dhm116/provider-upjet-authentik/apis/namespaced/flow/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this PermissionRole.
func (mg *PermissionRole) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ObjectID),
		Extract:      resource.ExtractParamPath("uuid", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ObjectIDRef,
		Selector:     mg.Spec.ForProvider.ObjectIDSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ObjectID")
	}
	mg.Spec.ForProvider.ObjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ObjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Role),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.RoleRef,
		Selector:     mg.Spec.ForProvider.RoleSelector,
		To: reference.To{
			List:    &v1alpha11.RoleList{},
			Managed: &v1alpha11.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Role")
	}
	mg.Spec.ForProvider.Role = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RoleRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ObjectID),
		Extract:      resource.ExtractParamPath("uuid", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ObjectIDRef,
		Selector:     mg.Spec.InitProvider.ObjectIDSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ObjectID")
	}
	mg.Spec.InitProvider.ObjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ObjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Role),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.RoleRef,
		Selector:     mg.Spec.InitProvider.RoleSelector,
		To: reference.To{
			List:    &v1alpha11.RoleList{},
			Managed: &v1alpha11.Role{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Role")
	}
	mg.Spec.InitProvider.Role = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.RoleRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this PermissionUser.
func (mg *PermissionUser) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ObjectID),
		Extract:      resource.ExtractParamPath("uuid", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ObjectIDRef,
		Selector:     mg.Spec.ForProvider.ObjectIDSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ObjectID")
	}
	mg.Spec.ForProvider.ObjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ObjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.User),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.UserRef,
		Selector:     mg.Spec.ForProvider.UserSelector,
		To: reference.To{
			List:    &v1alpha11.UserList{},
			Managed: &v1alpha11.User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.User")
	}
	mg.Spec.ForProvider.User = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.UserRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ObjectID),
		Extract:      resource.ExtractParamPath("uuid", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ObjectIDRef,
		Selector:     mg.Spec.InitProvider.ObjectIDSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ObjectID")
	}
	mg.Spec.InitProvider.ObjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ObjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.User),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.UserRef,
		Selector:     mg.Spec.InitProvider.UserSelector,
		To: reference.To{
			List:    &v1alpha11.UserList{},
			Managed: &v1alpha11.User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.User")
	}
	mg.Spec.InitProvider.User = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.UserRef = rsp.ResolvedReference

	return nil
}
