// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"

	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha1 "github.com/dhm116/provider-upjet-authentik/apis/cluster/stage/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this StageBinding.
func (mg *StageBinding) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Stage),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.StageRef,
		Selector:     mg.Spec.ForProvider.StageSelector,
		To: reference.To{
			List:    &v1alpha1.DummyList{},
			Managed: &v1alpha1.Dummy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Stage")
	}
	mg.Spec.ForProvider.Stage = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.StageRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Target),
		Extract:      resource.ExtractParamPath("uuid", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.TargetRef,
		Selector:     mg.Spec.ForProvider.TargetSelector,
		To: reference.To{
			List:    &FlowList{},
			Managed: &Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Target")
	}
	mg.Spec.ForProvider.Target = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.TargetRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Stage),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.StageRef,
		Selector:     mg.Spec.InitProvider.StageSelector,
		To: reference.To{
			List:    &v1alpha1.DummyList{},
			Managed: &v1alpha1.Dummy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Stage")
	}
	mg.Spec.InitProvider.Stage = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.StageRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Target),
		Extract:      resource.ExtractParamPath("uuid", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.TargetRef,
		Selector:     mg.Spec.InitProvider.TargetSelector,
		To: reference.To{
			List:    &FlowList{},
			Managed: &Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Target")
	}
	mg.Spec.InitProvider.Target = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.TargetRef = rsp.ResolvedReference

	return nil
}
