apiVersion: flow.authentik.m.goauthentik.io/v1alpha1
kind: Flow
metadata:
  annotations:
    meta.upbound.io/example-id: flow/v1alpha1/flow
  labels:
    testing.upbound.io/example-name: flow
  name: flow
  namespace: upbound-system
spec:
  forProvider:
    designation: authorization
    name: test-flow
    slug: test-flow
    title: Test flow

---

apiVersion: flow.authentik.m.goauthentik.io/v1alpha1
kind: StageBinding
metadata:
  annotations:
    meta.upbound.io/example-id: flow/v1alpha1/flow
  labels:
    testing.upbound.io/example-name: dummy-flow
  name: dummy-flow
  namespace: upbound-system
spec:
  forProvider:
    order: 0
    stageSelector:
      matchLabels:
        testing.upbound.io/example-name: name
    targetSelector:
      matchLabels:
        testing.upbound.io/example-name: flow

---

apiVersion: stage.authentik.m.goauthentik.io/v1alpha1
kind: Dummy
metadata:
  annotations:
    meta.upbound.io/example-id: flow/v1alpha1/flow
  labels:
    testing.upbound.io/example-name: name
  name: name
  namespace: upbound-system
spec:
  forProvider:
    name: test-stage
