apiVersion: endpoints.authentik.goauthentik.io/v1alpha1
kind: ConnectorAgentEnrollmentToken
metadata:
  annotations:
    meta.upbound.io/example-id: endpoints/v1alpha1/connectoragentenrollmenttoken
  labels:
    testing.upbound.io/example-name: token
  name: token
spec:
  forProvider:
    connectorSelector:
      matchLabels:
        testing.upbound.io/example-name: agent
    expiring: false
    name: my-enrollment token
    retrieveKey: true
