apiVersion: source.authentik.goauthentik.io/v1alpha1
kind: Oauth
metadata:
  annotations:
    meta.upbound.io/example-id: source/v1alpha1/oauth
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    authenticationFlow: ${data.authentik_flow.default-source-authentication.id}
    consumerKey: foo
    consumerSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    enrollmentFlow: ${data.authentik_flow.default-source-enrollment.id}
    name: discord
    providerType: discord
    slug: discord
