// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ConnectorAgentEnrollmentTokenInitParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/dhm116/provider-authentik/apis/cluster/endpoints/v1alpha1.ConnectorAgent
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	Connector *string `json:"connector,omitempty" tf:"connector,omitempty"`

	// Reference to a ConnectorAgent in endpoints to populate connector.
	// +kubebuilder:validation:Optional
	ConnectorRef *v2.Reference `json:"connectorRef,omitempty" tf:"-"`

	// Selector for a ConnectorAgent in endpoints to populate connector.
	// +kubebuilder:validation:Optional
	ConnectorSelector *v2.Selector `json:"connectorSelector,omitempty" tf:"-"`

	// (String)
	DeviceAccessGroup *string `json:"deviceAccessGroup,omitempty" tf:"device_access_group,omitempty"`

	// (String)
	Expires *string `json:"expires,omitempty" tf:"expires,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	Expiring *bool `json:"expiring,omitempty" tf:"expiring,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	RetrieveKey *bool `json:"retrieveKey,omitempty" tf:"retrieve_key,omitempty"`
}

type ConnectorAgentEnrollmentTokenObservation struct {

	// (String)
	Connector *string `json:"connector,omitempty" tf:"connector,omitempty"`

	// (String)
	DeviceAccessGroup *string `json:"deviceAccessGroup,omitempty" tf:"device_access_group,omitempty"`

	// (String)
	Expires *string `json:"expires,omitempty" tf:"expires,omitempty"`

	// (Number) Generated.
	// Generated.
	ExpiresIn *float64 `json:"expiresIn,omitempty" tf:"expires_in,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	Expiring *bool `json:"expiring,omitempty" tf:"expiring,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	RetrieveKey *bool `json:"retrieveKey,omitempty" tf:"retrieve_key,omitempty"`
}

type ConnectorAgentEnrollmentTokenParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/dhm116/provider-authentik/apis/cluster/endpoints/v1alpha1.ConnectorAgent
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	Connector *string `json:"connector,omitempty" tf:"connector,omitempty"`

	// Reference to a ConnectorAgent in endpoints to populate connector.
	// +kubebuilder:validation:Optional
	ConnectorRef *v2.Reference `json:"connectorRef,omitempty" tf:"-"`

	// Selector for a ConnectorAgent in endpoints to populate connector.
	// +kubebuilder:validation:Optional
	ConnectorSelector *v2.Selector `json:"connectorSelector,omitempty" tf:"-"`

	// (String)
	// +kubebuilder:validation:Optional
	DeviceAccessGroup *string `json:"deviceAccessGroup,omitempty" tf:"device_access_group,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Expires *string `json:"expires,omitempty" tf:"expires,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	Expiring *bool `json:"expiring,omitempty" tf:"expiring,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	RetrieveKey *bool `json:"retrieveKey,omitempty" tf:"retrieve_key,omitempty"`
}

// ConnectorAgentEnrollmentTokenSpec defines the desired state of ConnectorAgentEnrollmentToken
type ConnectorAgentEnrollmentTokenSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ConnectorAgentEnrollmentTokenParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConnectorAgentEnrollmentTokenInitParameters `json:"initProvider,omitempty"`
}

// ConnectorAgentEnrollmentTokenStatus defines the observed state of ConnectorAgentEnrollmentToken.
type ConnectorAgentEnrollmentTokenStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ConnectorAgentEnrollmentTokenObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ConnectorAgentEnrollmentToken is the Schema for the ConnectorAgentEnrollmentTokens API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type ConnectorAgentEnrollmentToken struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ConnectorAgentEnrollmentTokenSpec   `json:"spec"`
	Status ConnectorAgentEnrollmentTokenStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConnectorAgentEnrollmentTokenList contains a list of ConnectorAgentEnrollmentTokens
type ConnectorAgentEnrollmentTokenList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConnectorAgentEnrollmentToken `json:"items"`
}

// Repository type metadata.
var (
	ConnectorAgentEnrollmentToken_Kind             = "ConnectorAgentEnrollmentToken"
	ConnectorAgentEnrollmentToken_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ConnectorAgentEnrollmentToken_Kind}.String()
	ConnectorAgentEnrollmentToken_KindAPIVersion   = ConnectorAgentEnrollmentToken_Kind + "." + CRDGroupVersion.String()
	ConnectorAgentEnrollmentToken_GroupVersionKind = CRDGroupVersion.WithKind(ConnectorAgentEnrollmentToken_Kind)
)

func init() {
	SchemeBuilder.Register(&ConnectorAgentEnrollmentToken{}, &ConnectorAgentEnrollmentTokenList{})
}
