// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ConnectorAgentInitParameters struct {

	// Format: hours=1;minutes=2;seconds=3. Defaults to `hours=8`.
	AuthSessionDuration *string `json:"authSessionDuration,omitempty" tf:"auth_session_duration,omitempty"`

	// Defaults to `true`.
	AuthTerminateSessionOnExpiry *bool `json:"authTerminateSessionOnExpiry,omitempty" tf:"auth_terminate_session_on_expiry,omitempty"`

	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=3`.
	ChallengeIdleTimeout *string `json:"challengeIdleTimeout,omitempty" tf:"challenge_idle_timeout,omitempty"`

	ChallengeKey *string `json:"challengeKey,omitempty" tf:"challenge_key,omitempty"`

	// Defaults to `true`.
	ChallengeTriggerCheckIn *bool `json:"challengeTriggerCheckIn,omitempty" tf:"challenge_trigger_check_in,omitempty"`

	// Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	JwtFederationProviders []*float64 `json:"jwtFederationProviders,omitempty" tf:"jwt_federation_providers,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Defaults to `4000`.
	NssGIDOffset *float64 `json:"nssGidOffset,omitempty" tf:"nss_gid_offset,omitempty"`

	// Defaults to `2000`.
	NssUIDOffset *float64 `json:"nssUidOffset,omitempty" tf:"nss_uid_offset,omitempty"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
	RefreshInterval *string `json:"refreshInterval,omitempty" tf:"refresh_interval,omitempty"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `hours=24`.
	SnapshotExpiry *string `json:"snapshotExpiry,omitempty" tf:"snapshot_expiry,omitempty"`
}

type ConnectorAgentObservation struct {

	// Format: hours=1;minutes=2;seconds=3. Defaults to `hours=8`.
	AuthSessionDuration *string `json:"authSessionDuration,omitempty" tf:"auth_session_duration,omitempty"`

	// Defaults to `true`.
	AuthTerminateSessionOnExpiry *bool `json:"authTerminateSessionOnExpiry,omitempty" tf:"auth_terminate_session_on_expiry,omitempty"`

	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=3`.
	ChallengeIdleTimeout *string `json:"challengeIdleTimeout,omitempty" tf:"challenge_idle_timeout,omitempty"`

	ChallengeKey *string `json:"challengeKey,omitempty" tf:"challenge_key,omitempty"`

	// Defaults to `true`.
	ChallengeTriggerCheckIn *bool `json:"challengeTriggerCheckIn,omitempty" tf:"challenge_trigger_check_in,omitempty"`

	// Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	JwtFederationProviders []*float64 `json:"jwtFederationProviders,omitempty" tf:"jwt_federation_providers,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Defaults to `4000`.
	NssGIDOffset *float64 `json:"nssGidOffset,omitempty" tf:"nss_gid_offset,omitempty"`

	// Defaults to `2000`.
	NssUIDOffset *float64 `json:"nssUidOffset,omitempty" tf:"nss_uid_offset,omitempty"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
	RefreshInterval *string `json:"refreshInterval,omitempty" tf:"refresh_interval,omitempty"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `hours=24`.
	SnapshotExpiry *string `json:"snapshotExpiry,omitempty" tf:"snapshot_expiry,omitempty"`
}

type ConnectorAgentParameters struct {

	// Format: hours=1;minutes=2;seconds=3. Defaults to `hours=8`.
	// +kubebuilder:validation:Optional
	AuthSessionDuration *string `json:"authSessionDuration,omitempty" tf:"auth_session_duration,omitempty"`

	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	AuthTerminateSessionOnExpiry *bool `json:"authTerminateSessionOnExpiry,omitempty" tf:"auth_terminate_session_on_expiry,omitempty"`

	// +kubebuilder:validation:Optional
	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=3`.
	// +kubebuilder:validation:Optional
	ChallengeIdleTimeout *string `json:"challengeIdleTimeout,omitempty" tf:"challenge_idle_timeout,omitempty"`

	// +kubebuilder:validation:Optional
	ChallengeKey *string `json:"challengeKey,omitempty" tf:"challenge_key,omitempty"`

	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	ChallengeTriggerCheckIn *bool `json:"challengeTriggerCheckIn,omitempty" tf:"challenge_trigger_check_in,omitempty"`

	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	JwtFederationProviders []*float64 `json:"jwtFederationProviders,omitempty" tf:"jwt_federation_providers,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Defaults to `4000`.
	// +kubebuilder:validation:Optional
	NssGIDOffset *float64 `json:"nssGidOffset,omitempty" tf:"nss_gid_offset,omitempty"`

	// Defaults to `2000`.
	// +kubebuilder:validation:Optional
	NssUIDOffset *float64 `json:"nssUidOffset,omitempty" tf:"nss_uid_offset,omitempty"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
	// +kubebuilder:validation:Optional
	RefreshInterval *string `json:"refreshInterval,omitempty" tf:"refresh_interval,omitempty"`

	// Format: hours=1;minutes=2;seconds=3. Defaults to `hours=24`.
	// +kubebuilder:validation:Optional
	SnapshotExpiry *string `json:"snapshotExpiry,omitempty" tf:"snapshot_expiry,omitempty"`
}

// ConnectorAgentSpec defines the desired state of ConnectorAgent
type ConnectorAgentSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ConnectorAgentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConnectorAgentInitParameters `json:"initProvider,omitempty"`
}

// ConnectorAgentStatus defines the observed state of ConnectorAgent.
type ConnectorAgentStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ConnectorAgentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ConnectorAgent is the Schema for the ConnectorAgents API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type ConnectorAgent struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ConnectorAgentSpec   `json:"spec"`
	Status ConnectorAgentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConnectorAgentList contains a list of ConnectorAgents
type ConnectorAgentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConnectorAgent `json:"items"`
}

// Repository type metadata.
var (
	ConnectorAgent_Kind             = "ConnectorAgent"
	ConnectorAgent_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ConnectorAgent_Kind}.String()
	ConnectorAgent_KindAPIVersion   = ConnectorAgent_Kind + "." + CRDGroupVersion.String()
	ConnectorAgent_GroupVersionKind = CRDGroupVersion.WithKind(ConnectorAgent_Kind)
)

func init() {
	SchemeBuilder.Register(&ConnectorAgent{}, &ConnectorAgentList{})
}
