// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *ConnectorAgent) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ConnectorAgentEnrollmentToken) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DeviceAccessGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GoogleChromeConnector) Hub() {}
