//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Outpost) DeepCopyInto(out *Outpost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Outpost.
func (in *Outpost) DeepCopy() *Outpost {
	if in == nil {
		return nil
	}
	out := new(Outpost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Outpost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutpostInitParameters) DeepCopyInto(out *OutpostInitParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProtocolProviders != nil {
		in, out := &in.ProtocolProviders, &out.ProtocolProviders
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.ProtocolProvidersRefs != nil {
		in, out := &in.ProtocolProvidersRefs, &out.ProtocolProvidersRefs
		*out = make([]v2.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProtocolProvidersSelector != nil {
		in, out := &in.ProtocolProvidersSelector, &out.ProtocolProvidersSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceConnection != nil {
		in, out := &in.ServiceConnection, &out.ServiceConnection
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutpostInitParameters.
func (in *OutpostInitParameters) DeepCopy() *OutpostInitParameters {
	if in == nil {
		return nil
	}
	out := new(OutpostInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutpostList) DeepCopyInto(out *OutpostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Outpost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutpostList.
func (in *OutpostList) DeepCopy() *OutpostList {
	if in == nil {
		return nil
	}
	out := new(OutpostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OutpostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutpostObservation) DeepCopyInto(out *OutpostObservation) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProtocolProviders != nil {
		in, out := &in.ProtocolProviders, &out.ProtocolProviders
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.ServiceConnection != nil {
		in, out := &in.ServiceConnection, &out.ServiceConnection
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutpostObservation.
func (in *OutpostObservation) DeepCopy() *OutpostObservation {
	if in == nil {
		return nil
	}
	out := new(OutpostObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutpostParameters) DeepCopyInto(out *OutpostParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProtocolProviders != nil {
		in, out := &in.ProtocolProviders, &out.ProtocolProviders
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.ProtocolProvidersRefs != nil {
		in, out := &in.ProtocolProvidersRefs, &out.ProtocolProvidersRefs
		*out = make([]v2.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProtocolProvidersSelector != nil {
		in, out := &in.ProtocolProvidersSelector, &out.ProtocolProvidersSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceConnection != nil {
		in, out := &in.ServiceConnection, &out.ServiceConnection
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutpostParameters.
func (in *OutpostParameters) DeepCopy() *OutpostParameters {
	if in == nil {
		return nil
	}
	out := new(OutpostParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutpostSpec) DeepCopyInto(out *OutpostSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutpostSpec.
func (in *OutpostSpec) DeepCopy() *OutpostSpec {
	if in == nil {
		return nil
	}
	out := new(OutpostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutpostStatus) DeepCopyInto(out *OutpostStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutpostStatus.
func (in *OutpostStatus) DeepCopy() *OutpostStatus {
	if in == nil {
		return nil
	}
	out := new(OutpostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAttachment) DeepCopyInto(out *ProviderAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAttachment.
func (in *ProviderAttachment) DeepCopy() *ProviderAttachment {
	if in == nil {
		return nil
	}
	out := new(ProviderAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAttachmentInitParameters) DeepCopyInto(out *ProviderAttachmentInitParameters) {
	*out = *in
	if in.Outpost != nil {
		in, out := &in.Outpost, &out.Outpost
		*out = new(string)
		**out = **in
	}
	if in.OutpostRef != nil {
		in, out := &in.OutpostRef, &out.OutpostRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OutpostSelector != nil {
		in, out := &in.OutpostSelector, &out.OutpostSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ProtocolProvider != nil {
		in, out := &in.ProtocolProvider, &out.ProtocolProvider
		*out = new(float64)
		**out = **in
	}
	if in.ProtocolProviderRef != nil {
		in, out := &in.ProtocolProviderRef, &out.ProtocolProviderRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProtocolProviderSelector != nil {
		in, out := &in.ProtocolProviderSelector, &out.ProtocolProviderSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAttachmentInitParameters.
func (in *ProviderAttachmentInitParameters) DeepCopy() *ProviderAttachmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderAttachmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAttachmentList) DeepCopyInto(out *ProviderAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProviderAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAttachmentList.
func (in *ProviderAttachmentList) DeepCopy() *ProviderAttachmentList {
	if in == nil {
		return nil
	}
	out := new(ProviderAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAttachmentObservation) DeepCopyInto(out *ProviderAttachmentObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Outpost != nil {
		in, out := &in.Outpost, &out.Outpost
		*out = new(string)
		**out = **in
	}
	if in.ProtocolProvider != nil {
		in, out := &in.ProtocolProvider, &out.ProtocolProvider
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAttachmentObservation.
func (in *ProviderAttachmentObservation) DeepCopy() *ProviderAttachmentObservation {
	if in == nil {
		return nil
	}
	out := new(ProviderAttachmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAttachmentParameters) DeepCopyInto(out *ProviderAttachmentParameters) {
	*out = *in
	if in.Outpost != nil {
		in, out := &in.Outpost, &out.Outpost
		*out = new(string)
		**out = **in
	}
	if in.OutpostRef != nil {
		in, out := &in.OutpostRef, &out.OutpostRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.OutpostSelector != nil {
		in, out := &in.OutpostSelector, &out.OutpostSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ProtocolProvider != nil {
		in, out := &in.ProtocolProvider, &out.ProtocolProvider
		*out = new(float64)
		**out = **in
	}
	if in.ProtocolProviderRef != nil {
		in, out := &in.ProtocolProviderRef, &out.ProtocolProviderRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProtocolProviderSelector != nil {
		in, out := &in.ProtocolProviderSelector, &out.ProtocolProviderSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAttachmentParameters.
func (in *ProviderAttachmentParameters) DeepCopy() *ProviderAttachmentParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderAttachmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAttachmentSpec) DeepCopyInto(out *ProviderAttachmentSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAttachmentSpec.
func (in *ProviderAttachmentSpec) DeepCopy() *ProviderAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAttachmentStatus) DeepCopyInto(out *ProviderAttachmentStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAttachmentStatus.
func (in *ProviderAttachmentStatus) DeepCopy() *ProviderAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}
