apiVersion: source.authentik.m.goauthentik.io/v1alpha1
kind: Plex
metadata:
  annotations:
    meta.upbound.io/example-id: source/v1alpha1/plex
  labels:
    testing.upbound.io/example-name: name
  name: name
  namespace: upbound-system
spec:
  forProvider:
    authenticationFlow: ${data.authentik_flow.default-authorization-flow.id}
    clientId: foo-bar-baz
    enrollmentFlow: ${data.authentik_flow.default-authorization-flow.id}
    name: plex
    plexTokenSecretRef:
      key: example-key
      name: example-secret
    slug: plex
