// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SettingsInitParameters struct {

	// (String) Defaults to gravatar,initials.
	// Defaults to `gravatar,initials`.
	Avatars *string `json:"avatars,omitempty" tf:"avatars,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to minutes=30.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
	DefaultTokenDuration *string `json:"defaultTokenDuration,omitempty" tf:"default_token_duration,omitempty"`

	// (Number) Defaults to 60.
	// Defaults to `60`.
	DefaultTokenLength *float64 `json:"defaultTokenLength,omitempty" tf:"default_token_length,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	DefaultUserChangeEmail *bool `json:"defaultUserChangeEmail,omitempty" tf:"default_user_change_email,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	DefaultUserChangeName *bool `json:"defaultUserChangeName,omitempty" tf:"default_user_change_name,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	DefaultUserChangeUsername *bool `json:"defaultUserChangeUsername,omitempty" tf:"default_user_change_username,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to days=365.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `days=365`.
	EventRetention *string `json:"eventRetention,omitempty" tf:"event_retention,omitempty"`

	// (String) JSON format expected. Use jsonencode() to pass objects. Defaults to {"core_default_app_access":false,"enterprise_audit_include_expanded_diff":false,"flows_continuous_login":false,"flows_refresh_others":false}.
	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{"core_default_app_access":false,"enterprise_audit_include_expanded_diff":false,"flows_continuous_login":false,"flows_refresh_others":false}`.
	Flags *string `json:"flags,omitempty" tf:"flags,omitempty"`

	// (List of Map of String)
	FooterLinks []map[string]*string `json:"footerLinks,omitempty" tf:"footer_links,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	GdprCompliance *bool `json:"gdprCompliance,omitempty" tf:"gdpr_compliance,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	Impersonation *bool `json:"impersonation,omitempty" tf:"impersonation,omitempty"`

	// (Number) Defaults to 20.
	// Defaults to `20`.
	PaginationDefaultPageSize *float64 `json:"paginationDefaultPageSize,omitempty" tf:"pagination_default_page_size,omitempty"`

	// (Number) Defaults to 100.
	// Defaults to `100`.
	PaginationMaxPageSize *float64 `json:"paginationMaxPageSize,omitempty" tf:"pagination_max_page_size,omitempty"`

	// 5.
	// Defaults to `-5`.
	ReputationLowerLimit *float64 `json:"reputationLowerLimit,omitempty" tf:"reputation_lower_limit,omitempty"`

	// (Number) Defaults to 5.
	// Defaults to `5`.
	ReputationUpperLimit *float64 `json:"reputationUpperLimit,omitempty" tf:"reputation_upper_limit,omitempty"`
}

type SettingsObservation struct {

	// (String) Defaults to gravatar,initials.
	// Defaults to `gravatar,initials`.
	Avatars *string `json:"avatars,omitempty" tf:"avatars,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to minutes=30.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
	DefaultTokenDuration *string `json:"defaultTokenDuration,omitempty" tf:"default_token_duration,omitempty"`

	// (Number) Defaults to 60.
	// Defaults to `60`.
	DefaultTokenLength *float64 `json:"defaultTokenLength,omitempty" tf:"default_token_length,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	DefaultUserChangeEmail *bool `json:"defaultUserChangeEmail,omitempty" tf:"default_user_change_email,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	DefaultUserChangeName *bool `json:"defaultUserChangeName,omitempty" tf:"default_user_change_name,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	DefaultUserChangeUsername *bool `json:"defaultUserChangeUsername,omitempty" tf:"default_user_change_username,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to days=365.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `days=365`.
	EventRetention *string `json:"eventRetention,omitempty" tf:"event_retention,omitempty"`

	// (String) JSON format expected. Use jsonencode() to pass objects. Defaults to {"core_default_app_access":false,"enterprise_audit_include_expanded_diff":false,"flows_continuous_login":false,"flows_refresh_others":false}.
	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{"core_default_app_access":false,"enterprise_audit_include_expanded_diff":false,"flows_continuous_login":false,"flows_refresh_others":false}`.
	Flags *string `json:"flags,omitempty" tf:"flags,omitempty"`

	// (List of Map of String)
	FooterLinks []map[string]*string `json:"footerLinks,omitempty" tf:"footer_links,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	GdprCompliance *bool `json:"gdprCompliance,omitempty" tf:"gdpr_compliance,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	Impersonation *bool `json:"impersonation,omitempty" tf:"impersonation,omitempty"`

	// (Number) Defaults to 20.
	// Defaults to `20`.
	PaginationDefaultPageSize *float64 `json:"paginationDefaultPageSize,omitempty" tf:"pagination_default_page_size,omitempty"`

	// (Number) Defaults to 100.
	// Defaults to `100`.
	PaginationMaxPageSize *float64 `json:"paginationMaxPageSize,omitempty" tf:"pagination_max_page_size,omitempty"`

	// 5.
	// Defaults to `-5`.
	ReputationLowerLimit *float64 `json:"reputationLowerLimit,omitempty" tf:"reputation_lower_limit,omitempty"`

	// (Number) Defaults to 5.
	// Defaults to `5`.
	ReputationUpperLimit *float64 `json:"reputationUpperLimit,omitempty" tf:"reputation_upper_limit,omitempty"`
}

type SettingsParameters struct {

	// (String) Defaults to gravatar,initials.
	// Defaults to `gravatar,initials`.
	// +kubebuilder:validation:Optional
	Avatars *string `json:"avatars,omitempty" tf:"avatars,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to minutes=30.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
	// +kubebuilder:validation:Optional
	DefaultTokenDuration *string `json:"defaultTokenDuration,omitempty" tf:"default_token_duration,omitempty"`

	// (Number) Defaults to 60.
	// Defaults to `60`.
	// +kubebuilder:validation:Optional
	DefaultTokenLength *float64 `json:"defaultTokenLength,omitempty" tf:"default_token_length,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	DefaultUserChangeEmail *bool `json:"defaultUserChangeEmail,omitempty" tf:"default_user_change_email,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	DefaultUserChangeName *bool `json:"defaultUserChangeName,omitempty" tf:"default_user_change_name,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	DefaultUserChangeUsername *bool `json:"defaultUserChangeUsername,omitempty" tf:"default_user_change_username,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to days=365.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `days=365`.
	// +kubebuilder:validation:Optional
	EventRetention *string `json:"eventRetention,omitempty" tf:"event_retention,omitempty"`

	// (String) JSON format expected. Use jsonencode() to pass objects. Defaults to {"core_default_app_access":false,"enterprise_audit_include_expanded_diff":false,"flows_continuous_login":false,"flows_refresh_others":false}.
	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{"core_default_app_access":false,"enterprise_audit_include_expanded_diff":false,"flows_continuous_login":false,"flows_refresh_others":false}`.
	// +kubebuilder:validation:Optional
	Flags *string `json:"flags,omitempty" tf:"flags,omitempty"`

	// (List of Map of String)
	// +kubebuilder:validation:Optional
	FooterLinks []map[string]*string `json:"footerLinks,omitempty" tf:"footer_links,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	GdprCompliance *bool `json:"gdprCompliance,omitempty" tf:"gdpr_compliance,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	Impersonation *bool `json:"impersonation,omitempty" tf:"impersonation,omitempty"`

	// (Number) Defaults to 20.
	// Defaults to `20`.
	// +kubebuilder:validation:Optional
	PaginationDefaultPageSize *float64 `json:"paginationDefaultPageSize,omitempty" tf:"pagination_default_page_size,omitempty"`

	// (Number) Defaults to 100.
	// Defaults to `100`.
	// +kubebuilder:validation:Optional
	PaginationMaxPageSize *float64 `json:"paginationMaxPageSize,omitempty" tf:"pagination_max_page_size,omitempty"`

	// 5.
	// Defaults to `-5`.
	// +kubebuilder:validation:Optional
	ReputationLowerLimit *float64 `json:"reputationLowerLimit,omitempty" tf:"reputation_lower_limit,omitempty"`

	// (Number) Defaults to 5.
	// Defaults to `5`.
	// +kubebuilder:validation:Optional
	ReputationUpperLimit *float64 `json:"reputationUpperLimit,omitempty" tf:"reputation_upper_limit,omitempty"`
}

// SettingsSpec defines the desired state of Settings
type SettingsSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   SettingsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SettingsInitParameters `json:"initProvider,omitempty"`
}

// SettingsStatus defines the observed state of Settings.
type SettingsStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SettingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Settings is the Schema for the Settingss API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type Settings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SettingsSpec   `json:"spec"`
	Status            SettingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SettingsList contains a list of Settingss
type SettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Settings `json:"items"`
}

// Repository type metadata.
var (
	Settings_Kind             = "Settings"
	Settings_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Settings_Kind}.String()
	Settings_KindAPIVersion   = Settings_Kind + "." + CRDGroupVersion.String()
	Settings_GroupVersionKind = CRDGroupVersion.WithKind(Settings_Kind)
)

func init() {
	SchemeBuilder.Register(&Settings{}, &SettingsList{})
}
