apiVersion: task.authentik.goauthentik.io/v1alpha1
kind: Schedule
metadata:
  annotations:
    meta.upbound.io/example-id: task/v1alpha1/schedule
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    appModel: authentik_providers_scim.scimprovider
    crontab: 6 */4 * * 2
    modelIdSelector:
      matchLabels:
        testing.upbound.io/example-name: name

---

apiVersion: provider.authentik.goauthentik.io/v1alpha1
kind: Scim
metadata:
  annotations:
    meta.upbound.io/example-id: task/v1alpha1/schedule
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: name
    tokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    url: http://localhost
