// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha1 "github.com/dhm116/provider-authentik/apis/namespaced/provider/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Outpost.
func (mg *Outpost) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromFloatPtrValues(mg.Spec.ForProvider.ProtocolProviders),
		Extract:       resource.ExtractResourceID(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.ProtocolProvidersRefs,
		Selector:      mg.Spec.ForProvider.ProtocolProvidersSelector,
		To: reference.To{
			List:    &v1alpha1.ProxyList{},
			Managed: &v1alpha1.Proxy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProtocolProviders")
	}
	mg.Spec.ForProvider.ProtocolProviders = reference.ToFloatPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.ProtocolProvidersRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromFloatPtrValues(mg.Spec.InitProvider.ProtocolProviders),
		Extract:       resource.ExtractResourceID(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.ProtocolProvidersRefs,
		Selector:      mg.Spec.InitProvider.ProtocolProvidersSelector,
		To: reference.To{
			List:    &v1alpha1.ProxyList{},
			Managed: &v1alpha1.Proxy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProtocolProviders")
	}
	mg.Spec.InitProvider.ProtocolProviders = reference.ToFloatPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.ProtocolProvidersRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this ProviderAttachment.
func (mg *ProviderAttachment) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Outpost),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.OutpostRef,
		Selector:     mg.Spec.ForProvider.OutpostSelector,
		To: reference.To{
			List:    &OutpostList{},
			Managed: &Outpost{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Outpost")
	}
	mg.Spec.ForProvider.Outpost = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OutpostRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.ProtocolProvider),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProtocolProviderRef,
		Selector:     mg.Spec.ForProvider.ProtocolProviderSelector,
		To: reference.To{
			List:    &v1alpha1.ProxyList{},
			Managed: &v1alpha1.Proxy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProtocolProvider")
	}
	mg.Spec.ForProvider.ProtocolProvider = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProtocolProviderRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Outpost),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.OutpostRef,
		Selector:     mg.Spec.InitProvider.OutpostSelector,
		To: reference.To{
			List:    &OutpostList{},
			Managed: &Outpost{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Outpost")
	}
	mg.Spec.InitProvider.Outpost = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.OutpostRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.ProtocolProvider),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProtocolProviderRef,
		Selector:     mg.Spec.InitProvider.ProtocolProviderSelector,
		To: reference.To{
			List:    &v1alpha1.ProxyList{},
			Managed: &v1alpha1.Proxy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProtocolProvider")
	}
	mg.Spec.InitProvider.ProtocolProvider = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProtocolProviderRef = rsp.ResolvedReference

	return nil
}
