// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SsfInitParameters struct {

	// Format: hours=1;minutes=2;seconds=3. Defaults to `days=30`.
	EventRetention *string `json:"eventRetention,omitempty" tf:"event_retention,omitempty"`

	// JWTs issued by any of the configured providers can be used to authenticate on behalf of this provider.
	JwtFederationProviders []*float64 `json:"jwtFederationProviders,omitempty" tf:"jwt_federation_providers,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Defaults to `true`.
	PushVerifyCertificates *bool `json:"pushVerifyCertificates,omitempty" tf:"push_verify_certificates,omitempty"`

	SigningKey *string `json:"signingKey,omitempty" tf:"signing_key,omitempty"`
}

type SsfObservation struct {

	// Format: hours=1;minutes=2;seconds=3. Defaults to `days=30`.
	EventRetention *string `json:"eventRetention,omitempty" tf:"event_retention,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// JWTs issued by any of the configured providers can be used to authenticate on behalf of this provider.
	JwtFederationProviders []*float64 `json:"jwtFederationProviders,omitempty" tf:"jwt_federation_providers,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Defaults to `true`.
	PushVerifyCertificates *bool `json:"pushVerifyCertificates,omitempty" tf:"push_verify_certificates,omitempty"`

	SigningKey *string `json:"signingKey,omitempty" tf:"signing_key,omitempty"`
}

type SsfParameters struct {

	// Format: hours=1;minutes=2;seconds=3. Defaults to `days=30`.
	// +kubebuilder:validation:Optional
	EventRetention *string `json:"eventRetention,omitempty" tf:"event_retention,omitempty"`

	// JWTs issued by any of the configured providers can be used to authenticate on behalf of this provider.
	// +kubebuilder:validation:Optional
	JwtFederationProviders []*float64 `json:"jwtFederationProviders,omitempty" tf:"jwt_federation_providers,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	PushVerifyCertificates *bool `json:"pushVerifyCertificates,omitempty" tf:"push_verify_certificates,omitempty"`

	// +kubebuilder:validation:Optional
	SigningKey *string `json:"signingKey,omitempty" tf:"signing_key,omitempty"`
}

// SsfSpec defines the desired state of Ssf
type SsfSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   SsfParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SsfInitParameters `json:"initProvider,omitempty"`
}

// SsfStatus defines the observed state of Ssf.
type SsfStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SsfObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Ssf is the Schema for the Ssfs API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type Ssf struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   SsfSpec   `json:"spec"`
	Status SsfStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SsfList contains a list of Ssfs
type SsfList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Ssf `json:"items"`
}

// Repository type metadata.
var (
	Ssf_Kind             = "Ssf"
	Ssf_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Ssf_Kind}.String()
	Ssf_KindAPIVersion   = Ssf_Kind + "." + CRDGroupVersion.String()
	Ssf_GroupVersionKind = CRDGroupVersion.WithKind(Ssf_Kind)
)

func init() {
	SchemeBuilder.Register(&Ssf{}, &SsfList{})
}
