// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *MappingNotification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MappingProviderGoogleWorkspace) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MappingProviderMicrosoftEntra) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MappingProviderRac) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MappingProviderRadius) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MappingProviderSAML) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MappingProviderScim) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MappingProviderScope) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MappingSourceKerberos) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MappingSourceLdap) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MappingSourceOauth) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MappingSourcePlex) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MappingSourceSAML) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MappingSourceScim) Hub() {}
