// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type MappingProviderRadiusInitParameters struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MappingProviderRadiusObservation struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MappingProviderRadiusParameters struct {

	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// MappingProviderRadiusSpec defines the desired state of MappingProviderRadius
type MappingProviderRadiusSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   MappingProviderRadiusParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MappingProviderRadiusInitParameters `json:"initProvider,omitempty"`
}

// MappingProviderRadiusStatus defines the observed state of MappingProviderRadius.
type MappingProviderRadiusStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               MappingProviderRadiusObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MappingProviderRadius is the Schema for the MappingProviderRadiuss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type MappingProviderRadius struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.expression) || (has(self.initProvider) && has(self.initProvider.expression))",message="spec.forProvider.expression is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   MappingProviderRadiusSpec   `json:"spec"`
	Status MappingProviderRadiusStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MappingProviderRadiusList contains a list of MappingProviderRadiuss
type MappingProviderRadiusList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MappingProviderRadius `json:"items"`
}

// Repository type metadata.
var (
	MappingProviderRadius_Kind             = "MappingProviderRadius"
	MappingProviderRadius_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MappingProviderRadius_Kind}.String()
	MappingProviderRadius_KindAPIVersion   = MappingProviderRadius_Kind + "." + CRDGroupVersion.String()
	MappingProviderRadius_GroupVersionKind = CRDGroupVersion.WithKind(MappingProviderRadius_Kind)
)

func init() {
	SchemeBuilder.Register(&MappingProviderRadius{}, &MappingProviderRadiusList{})
}
