// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type MappingProviderGoogleWorkspaceInitParameters struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MappingProviderGoogleWorkspaceObservation struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MappingProviderGoogleWorkspaceParameters struct {

	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// MappingProviderGoogleWorkspaceSpec defines the desired state of MappingProviderGoogleWorkspace
type MappingProviderGoogleWorkspaceSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   MappingProviderGoogleWorkspaceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MappingProviderGoogleWorkspaceInitParameters `json:"initProvider,omitempty"`
}

// MappingProviderGoogleWorkspaceStatus defines the observed state of MappingProviderGoogleWorkspace.
type MappingProviderGoogleWorkspaceStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               MappingProviderGoogleWorkspaceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MappingProviderGoogleWorkspace is the Schema for the MappingProviderGoogleWorkspaces API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type MappingProviderGoogleWorkspace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.expression) || (has(self.initProvider) && has(self.initProvider.expression))",message="spec.forProvider.expression is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   MappingProviderGoogleWorkspaceSpec   `json:"spec"`
	Status MappingProviderGoogleWorkspaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MappingProviderGoogleWorkspaceList contains a list of MappingProviderGoogleWorkspaces
type MappingProviderGoogleWorkspaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MappingProviderGoogleWorkspace `json:"items"`
}

// Repository type metadata.
var (
	MappingProviderGoogleWorkspace_Kind             = "MappingProviderGoogleWorkspace"
	MappingProviderGoogleWorkspace_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MappingProviderGoogleWorkspace_Kind}.String()
	MappingProviderGoogleWorkspace_KindAPIVersion   = MappingProviderGoogleWorkspace_Kind + "." + CRDGroupVersion.String()
	MappingProviderGoogleWorkspace_GroupVersionKind = CRDGroupVersion.WithKind(MappingProviderGoogleWorkspace_Kind)
)

func init() {
	SchemeBuilder.Register(&MappingProviderGoogleWorkspace{}, &MappingProviderGoogleWorkspaceList{})
}
