// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type MappingProviderRacInitParameters struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	Settings *string `json:"settings,omitempty" tf:"settings,omitempty"`
}

type MappingProviderRacObservation struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	Settings *string `json:"settings,omitempty" tf:"settings,omitempty"`
}

type MappingProviderRacParameters struct {

	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	// +kubebuilder:validation:Optional
	Settings *string `json:"settings,omitempty" tf:"settings,omitempty"`
}

// MappingProviderRacSpec defines the desired state of MappingProviderRac
type MappingProviderRacSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   MappingProviderRacParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MappingProviderRacInitParameters `json:"initProvider,omitempty"`
}

// MappingProviderRacStatus defines the observed state of MappingProviderRac.
type MappingProviderRacStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               MappingProviderRacObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MappingProviderRac is the Schema for the MappingProviderRacs API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type MappingProviderRac struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   MappingProviderRacSpec   `json:"spec"`
	Status MappingProviderRacStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MappingProviderRacList contains a list of MappingProviderRacs
type MappingProviderRacList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MappingProviderRac `json:"items"`
}

// Repository type metadata.
var (
	MappingProviderRac_Kind             = "MappingProviderRac"
	MappingProviderRac_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MappingProviderRac_Kind}.String()
	MappingProviderRac_KindAPIVersion   = MappingProviderRac_Kind + "." + CRDGroupVersion.String()
	MappingProviderRac_GroupVersionKind = CRDGroupVersion.WithKind(MappingProviderRac_Kind)
)

func init() {
	SchemeBuilder.Register(&MappingProviderRac{}, &MappingProviderRacList{})
}
