apiVersion: serviceconnection.authentik.m.goauthentik.io/v1alpha1
kind: Docker
metadata:
  annotations:
    meta.upbound.io/example-id: serviceconnection/v1alpha1/docker
  labels:
    testing.upbound.io/example-name: local
  name: local
  namespace: upbound-system
spec:
  forProvider:
    local: true
    name: local

---

apiVersion: certificate.authentik.m.goauthentik.io/v1alpha1
kind: KeyPair
metadata:
  annotations:
    meta.upbound.io/example-id: serviceconnection/v1alpha1/docker
  labels:
    testing.upbound.io/example-name: tls-auth
  name: tls-auth
  namespace: upbound-system
spec:
  forProvider:
    certificateData: '...'
    keyDataSecretRef:
      key: example-key
      name: example-secret
    name: docker-tls-auth

---

apiVersion: certificate.authentik.m.goauthentik.io/v1alpha1
kind: KeyPair
metadata:
  annotations:
    meta.upbound.io/example-id: serviceconnection/v1alpha1/docker
  labels:
    testing.upbound.io/example-name: tls-verification
  name: tls-verification
  namespace: upbound-system
spec:
  forProvider:
    certificateData: '...'
    name: docker-tls-verification
