apiVersion: stage.authentik.m.goauthentik.io/v1alpha1
kind: AuthenticatorTotp
metadata:
  annotations:
    meta.upbound.io/example-id: stage/v1alpha1/authenticatortotp
  labels:
    testing.upbound.io/example-name: name
  name: name
  namespace: upbound-system
spec:
  forProvider:
    name: totp-setup
