// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type GoogleChromeConnectorInitParameters struct {

	// (String) JSON format expected. Use jsonencode() to pass objects.
	// JSON format expected. Use `jsonencode()` to pass objects.
	Credentials *string `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type GoogleChromeConnectorObservation struct {

	// (String) Generated.
	// Generated.
	ChromeURL *string `json:"chromeUrl,omitempty" tf:"chrome_url,omitempty"`

	// (String) JSON format expected. Use jsonencode() to pass objects.
	// JSON format expected. Use `jsonencode()` to pass objects.
	Credentials *string `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type GoogleChromeConnectorParameters struct {

	// (String) JSON format expected. Use jsonencode() to pass objects.
	// JSON format expected. Use `jsonencode()` to pass objects.
	// +kubebuilder:validation:Optional
	Credentials *string `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// GoogleChromeConnectorSpec defines the desired state of GoogleChromeConnector
type GoogleChromeConnectorSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GoogleChromeConnectorParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GoogleChromeConnectorInitParameters `json:"initProvider,omitempty"`
}

// GoogleChromeConnectorStatus defines the observed state of GoogleChromeConnector.
type GoogleChromeConnectorStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               GoogleChromeConnectorObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GoogleChromeConnector is the Schema for the GoogleChromeConnectors API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,authentik}
type GoogleChromeConnector struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.credentials) || (has(self.initProvider) && has(self.initProvider.credentials))",message="spec.forProvider.credentials is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   GoogleChromeConnectorSpec   `json:"spec"`
	Status GoogleChromeConnectorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GoogleChromeConnectorList contains a list of GoogleChromeConnectors
type GoogleChromeConnectorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GoogleChromeConnector `json:"items"`
}

// Repository type metadata.
var (
	GoogleChromeConnector_Kind             = "GoogleChromeConnector"
	GoogleChromeConnector_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GoogleChromeConnector_Kind}.String()
	GoogleChromeConnector_KindAPIVersion   = GoogleChromeConnector_Kind + "." + CRDGroupVersion.String()
	GoogleChromeConnector_GroupVersionKind = CRDGroupVersion.WithKind(GoogleChromeConnector_Kind)
)

func init() {
	SchemeBuilder.Register(&GoogleChromeConnector{}, &GoogleChromeConnectorList{})
}
