//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAgent) DeepCopyInto(out *ConnectorAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAgent.
func (in *ConnectorAgent) DeepCopy() *ConnectorAgent {
	if in == nil {
		return nil
	}
	out := new(ConnectorAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAgentEnrollmentToken) DeepCopyInto(out *ConnectorAgentEnrollmentToken) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAgentEnrollmentToken.
func (in *ConnectorAgentEnrollmentToken) DeepCopy() *ConnectorAgentEnrollmentToken {
	if in == nil {
		return nil
	}
	out := new(ConnectorAgentEnrollmentToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorAgentEnrollmentToken) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAgentEnrollmentTokenInitParameters) DeepCopyInto(out *ConnectorAgentEnrollmentTokenInitParameters) {
	*out = *in
	if in.Connector != nil {
		in, out := &in.Connector, &out.Connector
		*out = new(string)
		**out = **in
	}
	if in.ConnectorRef != nil {
		in, out := &in.ConnectorRef, &out.ConnectorRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectorSelector != nil {
		in, out := &in.ConnectorSelector, &out.ConnectorSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DeviceAccessGroup != nil {
		in, out := &in.DeviceAccessGroup, &out.DeviceAccessGroup
		*out = new(string)
		**out = **in
	}
	if in.Expires != nil {
		in, out := &in.Expires, &out.Expires
		*out = new(string)
		**out = **in
	}
	if in.Expiring != nil {
		in, out := &in.Expiring, &out.Expiring
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RetrieveKey != nil {
		in, out := &in.RetrieveKey, &out.RetrieveKey
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAgentEnrollmentTokenInitParameters.
func (in *ConnectorAgentEnrollmentTokenInitParameters) DeepCopy() *ConnectorAgentEnrollmentTokenInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConnectorAgentEnrollmentTokenInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAgentEnrollmentTokenList) DeepCopyInto(out *ConnectorAgentEnrollmentTokenList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConnectorAgentEnrollmentToken, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAgentEnrollmentTokenList.
func (in *ConnectorAgentEnrollmentTokenList) DeepCopy() *ConnectorAgentEnrollmentTokenList {
	if in == nil {
		return nil
	}
	out := new(ConnectorAgentEnrollmentTokenList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorAgentEnrollmentTokenList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAgentEnrollmentTokenObservation) DeepCopyInto(out *ConnectorAgentEnrollmentTokenObservation) {
	*out = *in
	if in.Connector != nil {
		in, out := &in.Connector, &out.Connector
		*out = new(string)
		**out = **in
	}
	if in.DeviceAccessGroup != nil {
		in, out := &in.DeviceAccessGroup, &out.DeviceAccessGroup
		*out = new(string)
		**out = **in
	}
	if in.Expires != nil {
		in, out := &in.Expires, &out.Expires
		*out = new(string)
		**out = **in
	}
	if in.ExpiresIn != nil {
		in, out := &in.ExpiresIn, &out.ExpiresIn
		*out = new(float64)
		**out = **in
	}
	if in.Expiring != nil {
		in, out := &in.Expiring, &out.Expiring
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RetrieveKey != nil {
		in, out := &in.RetrieveKey, &out.RetrieveKey
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAgentEnrollmentTokenObservation.
func (in *ConnectorAgentEnrollmentTokenObservation) DeepCopy() *ConnectorAgentEnrollmentTokenObservation {
	if in == nil {
		return nil
	}
	out := new(ConnectorAgentEnrollmentTokenObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAgentEnrollmentTokenParameters) DeepCopyInto(out *ConnectorAgentEnrollmentTokenParameters) {
	*out = *in
	if in.Connector != nil {
		in, out := &in.Connector, &out.Connector
		*out = new(string)
		**out = **in
	}
	if in.ConnectorRef != nil {
		in, out := &in.ConnectorRef, &out.ConnectorRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectorSelector != nil {
		in, out := &in.ConnectorSelector, &out.ConnectorSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DeviceAccessGroup != nil {
		in, out := &in.DeviceAccessGroup, &out.DeviceAccessGroup
		*out = new(string)
		**out = **in
	}
	if in.Expires != nil {
		in, out := &in.Expires, &out.Expires
		*out = new(string)
		**out = **in
	}
	if in.Expiring != nil {
		in, out := &in.Expiring, &out.Expiring
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RetrieveKey != nil {
		in, out := &in.RetrieveKey, &out.RetrieveKey
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAgentEnrollmentTokenParameters.
func (in *ConnectorAgentEnrollmentTokenParameters) DeepCopy() *ConnectorAgentEnrollmentTokenParameters {
	if in == nil {
		return nil
	}
	out := new(ConnectorAgentEnrollmentTokenParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAgentEnrollmentTokenSpec) DeepCopyInto(out *ConnectorAgentEnrollmentTokenSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAgentEnrollmentTokenSpec.
func (in *ConnectorAgentEnrollmentTokenSpec) DeepCopy() *ConnectorAgentEnrollmentTokenSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectorAgentEnrollmentTokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAgentEnrollmentTokenStatus) DeepCopyInto(out *ConnectorAgentEnrollmentTokenStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAgentEnrollmentTokenStatus.
func (in *ConnectorAgentEnrollmentTokenStatus) DeepCopy() *ConnectorAgentEnrollmentTokenStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectorAgentEnrollmentTokenStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAgentInitParameters) DeepCopyInto(out *ConnectorAgentInitParameters) {
	*out = *in
	if in.AuthSessionDuration != nil {
		in, out := &in.AuthSessionDuration, &out.AuthSessionDuration
		*out = new(string)
		**out = **in
	}
	if in.AuthTerminateSessionOnExpiry != nil {
		in, out := &in.AuthTerminateSessionOnExpiry, &out.AuthTerminateSessionOnExpiry
		*out = new(bool)
		**out = **in
	}
	if in.AuthorizationFlow != nil {
		in, out := &in.AuthorizationFlow, &out.AuthorizationFlow
		*out = new(string)
		**out = **in
	}
	if in.ChallengeIdleTimeout != nil {
		in, out := &in.ChallengeIdleTimeout, &out.ChallengeIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.ChallengeKey != nil {
		in, out := &in.ChallengeKey, &out.ChallengeKey
		*out = new(string)
		**out = **in
	}
	if in.ChallengeTriggerCheckIn != nil {
		in, out := &in.ChallengeTriggerCheckIn, &out.ChallengeTriggerCheckIn
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.JwtFederationProviders != nil {
		in, out := &in.JwtFederationProviders, &out.JwtFederationProviders
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NssGIDOffset != nil {
		in, out := &in.NssGIDOffset, &out.NssGIDOffset
		*out = new(float64)
		**out = **in
	}
	if in.NssUIDOffset != nil {
		in, out := &in.NssUIDOffset, &out.NssUIDOffset
		*out = new(float64)
		**out = **in
	}
	if in.RefreshInterval != nil {
		in, out := &in.RefreshInterval, &out.RefreshInterval
		*out = new(string)
		**out = **in
	}
	if in.SnapshotExpiry != nil {
		in, out := &in.SnapshotExpiry, &out.SnapshotExpiry
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAgentInitParameters.
func (in *ConnectorAgentInitParameters) DeepCopy() *ConnectorAgentInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConnectorAgentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAgentList) DeepCopyInto(out *ConnectorAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConnectorAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAgentList.
func (in *ConnectorAgentList) DeepCopy() *ConnectorAgentList {
	if in == nil {
		return nil
	}
	out := new(ConnectorAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAgentObservation) DeepCopyInto(out *ConnectorAgentObservation) {
	*out = *in
	if in.AuthSessionDuration != nil {
		in, out := &in.AuthSessionDuration, &out.AuthSessionDuration
		*out = new(string)
		**out = **in
	}
	if in.AuthTerminateSessionOnExpiry != nil {
		in, out := &in.AuthTerminateSessionOnExpiry, &out.AuthTerminateSessionOnExpiry
		*out = new(bool)
		**out = **in
	}
	if in.AuthorizationFlow != nil {
		in, out := &in.AuthorizationFlow, &out.AuthorizationFlow
		*out = new(string)
		**out = **in
	}
	if in.ChallengeIdleTimeout != nil {
		in, out := &in.ChallengeIdleTimeout, &out.ChallengeIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.ChallengeKey != nil {
		in, out := &in.ChallengeKey, &out.ChallengeKey
		*out = new(string)
		**out = **in
	}
	if in.ChallengeTriggerCheckIn != nil {
		in, out := &in.ChallengeTriggerCheckIn, &out.ChallengeTriggerCheckIn
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.JwtFederationProviders != nil {
		in, out := &in.JwtFederationProviders, &out.JwtFederationProviders
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NssGIDOffset != nil {
		in, out := &in.NssGIDOffset, &out.NssGIDOffset
		*out = new(float64)
		**out = **in
	}
	if in.NssUIDOffset != nil {
		in, out := &in.NssUIDOffset, &out.NssUIDOffset
		*out = new(float64)
		**out = **in
	}
	if in.RefreshInterval != nil {
		in, out := &in.RefreshInterval, &out.RefreshInterval
		*out = new(string)
		**out = **in
	}
	if in.SnapshotExpiry != nil {
		in, out := &in.SnapshotExpiry, &out.SnapshotExpiry
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAgentObservation.
func (in *ConnectorAgentObservation) DeepCopy() *ConnectorAgentObservation {
	if in == nil {
		return nil
	}
	out := new(ConnectorAgentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAgentParameters) DeepCopyInto(out *ConnectorAgentParameters) {
	*out = *in
	if in.AuthSessionDuration != nil {
		in, out := &in.AuthSessionDuration, &out.AuthSessionDuration
		*out = new(string)
		**out = **in
	}
	if in.AuthTerminateSessionOnExpiry != nil {
		in, out := &in.AuthTerminateSessionOnExpiry, &out.AuthTerminateSessionOnExpiry
		*out = new(bool)
		**out = **in
	}
	if in.AuthorizationFlow != nil {
		in, out := &in.AuthorizationFlow, &out.AuthorizationFlow
		*out = new(string)
		**out = **in
	}
	if in.ChallengeIdleTimeout != nil {
		in, out := &in.ChallengeIdleTimeout, &out.ChallengeIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.ChallengeKey != nil {
		in, out := &in.ChallengeKey, &out.ChallengeKey
		*out = new(string)
		**out = **in
	}
	if in.ChallengeTriggerCheckIn != nil {
		in, out := &in.ChallengeTriggerCheckIn, &out.ChallengeTriggerCheckIn
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.JwtFederationProviders != nil {
		in, out := &in.JwtFederationProviders, &out.JwtFederationProviders
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NssGIDOffset != nil {
		in, out := &in.NssGIDOffset, &out.NssGIDOffset
		*out = new(float64)
		**out = **in
	}
	if in.NssUIDOffset != nil {
		in, out := &in.NssUIDOffset, &out.NssUIDOffset
		*out = new(float64)
		**out = **in
	}
	if in.RefreshInterval != nil {
		in, out := &in.RefreshInterval, &out.RefreshInterval
		*out = new(string)
		**out = **in
	}
	if in.SnapshotExpiry != nil {
		in, out := &in.SnapshotExpiry, &out.SnapshotExpiry
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAgentParameters.
func (in *ConnectorAgentParameters) DeepCopy() *ConnectorAgentParameters {
	if in == nil {
		return nil
	}
	out := new(ConnectorAgentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAgentSpec) DeepCopyInto(out *ConnectorAgentSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAgentSpec.
func (in *ConnectorAgentSpec) DeepCopy() *ConnectorAgentSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectorAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorAgentStatus) DeepCopyInto(out *ConnectorAgentStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorAgentStatus.
func (in *ConnectorAgentStatus) DeepCopy() *ConnectorAgentStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectorAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceAccessGroup) DeepCopyInto(out *DeviceAccessGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceAccessGroup.
func (in *DeviceAccessGroup) DeepCopy() *DeviceAccessGroup {
	if in == nil {
		return nil
	}
	out := new(DeviceAccessGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceAccessGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceAccessGroupInitParameters) DeepCopyInto(out *DeviceAccessGroupInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceAccessGroupInitParameters.
func (in *DeviceAccessGroupInitParameters) DeepCopy() *DeviceAccessGroupInitParameters {
	if in == nil {
		return nil
	}
	out := new(DeviceAccessGroupInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceAccessGroupList) DeepCopyInto(out *DeviceAccessGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeviceAccessGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceAccessGroupList.
func (in *DeviceAccessGroupList) DeepCopy() *DeviceAccessGroupList {
	if in == nil {
		return nil
	}
	out := new(DeviceAccessGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceAccessGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceAccessGroupObservation) DeepCopyInto(out *DeviceAccessGroupObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceAccessGroupObservation.
func (in *DeviceAccessGroupObservation) DeepCopy() *DeviceAccessGroupObservation {
	if in == nil {
		return nil
	}
	out := new(DeviceAccessGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceAccessGroupParameters) DeepCopyInto(out *DeviceAccessGroupParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceAccessGroupParameters.
func (in *DeviceAccessGroupParameters) DeepCopy() *DeviceAccessGroupParameters {
	if in == nil {
		return nil
	}
	out := new(DeviceAccessGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceAccessGroupSpec) DeepCopyInto(out *DeviceAccessGroupSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceAccessGroupSpec.
func (in *DeviceAccessGroupSpec) DeepCopy() *DeviceAccessGroupSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceAccessGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceAccessGroupStatus) DeepCopyInto(out *DeviceAccessGroupStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceAccessGroupStatus.
func (in *DeviceAccessGroupStatus) DeepCopy() *DeviceAccessGroupStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceAccessGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleChromeConnector) DeepCopyInto(out *GoogleChromeConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleChromeConnector.
func (in *GoogleChromeConnector) DeepCopy() *GoogleChromeConnector {
	if in == nil {
		return nil
	}
	out := new(GoogleChromeConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GoogleChromeConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleChromeConnectorInitParameters) DeepCopyInto(out *GoogleChromeConnectorInitParameters) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleChromeConnectorInitParameters.
func (in *GoogleChromeConnectorInitParameters) DeepCopy() *GoogleChromeConnectorInitParameters {
	if in == nil {
		return nil
	}
	out := new(GoogleChromeConnectorInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleChromeConnectorList) DeepCopyInto(out *GoogleChromeConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GoogleChromeConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleChromeConnectorList.
func (in *GoogleChromeConnectorList) DeepCopy() *GoogleChromeConnectorList {
	if in == nil {
		return nil
	}
	out := new(GoogleChromeConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GoogleChromeConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleChromeConnectorObservation) DeepCopyInto(out *GoogleChromeConnectorObservation) {
	*out = *in
	if in.ChromeURL != nil {
		in, out := &in.ChromeURL, &out.ChromeURL
		*out = new(string)
		**out = **in
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleChromeConnectorObservation.
func (in *GoogleChromeConnectorObservation) DeepCopy() *GoogleChromeConnectorObservation {
	if in == nil {
		return nil
	}
	out := new(GoogleChromeConnectorObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleChromeConnectorParameters) DeepCopyInto(out *GoogleChromeConnectorParameters) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleChromeConnectorParameters.
func (in *GoogleChromeConnectorParameters) DeepCopy() *GoogleChromeConnectorParameters {
	if in == nil {
		return nil
	}
	out := new(GoogleChromeConnectorParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleChromeConnectorSpec) DeepCopyInto(out *GoogleChromeConnectorSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleChromeConnectorSpec.
func (in *GoogleChromeConnectorSpec) DeepCopy() *GoogleChromeConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(GoogleChromeConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleChromeConnectorStatus) DeepCopyInto(out *GoogleChromeConnectorStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleChromeConnectorStatus.
func (in *GoogleChromeConnectorStatus) DeepCopy() *GoogleChromeConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(GoogleChromeConnectorStatus)
	in.DeepCopyInto(out)
	return out
}
